FROM python:3.10

ENV PYTHONUNBUFFERED=1
ENV PYTHONBREAKPOINT=ipdb.set_trace

WORKDIR /twist/

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y postgresql-client # In order to use pg_dump

EXPOSE 8000
