version: '3.8'
services:
  db:
    image: postgres:11-alpine
    platform: linux/amd64
    restart: always
    environment:
      - POSTGRES_USER=twistdbadmin
      - POSTGRES_PASSWORD=76697421
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  redis:
    image: amd64/redis
    platform: linux/amd64
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  db:
    driver: local
  redis:
    driver: local

