version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: docker/common/Dockerfile.db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twistdbadmin"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  django:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.django
    command: ./manage.py makemigrations
    volumes:
      - .:/twist
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  db: {}
