version: '3.8'

volumes:
  django_static_vol: {}
  db:
    driver: local
    driver_opts:
      type: none
      device: /twist-db
      o: bind

services:
  db:
    build:
      context: .
      dockerfile: docker/common/Dockerfile.db
    platform: linux/amd64
    restart: always
    environment:
      - POSTGRES_USER=twistdbadmin
      - POSTGRES_PASSWORD=76697421
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twistdbadmin"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    restart: always
    build:
      context: .
      dockerfile: docker/prod/Dockerfile.celery
    command: celery -A twist worker -l INFO
    depends_on:
      redis:
        condition: service_healthy

  django:
    restart: always
    build:
      context: .
      dockerfile: docker/prod/Dockerfile.django
    command: ./prod-setup.sh
    # REMOVE
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
