version: '3.8'

volumes:
  django_static_vol: {}
  db: {}


services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    platform: linux/amd64
    restart: always
    environment:
      - POSTGRES_USER=twistdbadmin
      - POSTGRES_PASSWORD=76697421
    volumes:
      - db:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twistdbadmin"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.celery.prod
    command: celery -A twist worker -l INFO
    depends_on:
      redis:
        condition: service_healthy

  django:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: ./prod-setup.sh
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
