version: '3.8'

volumes:
  caddy_static_vol:
    driver: local
  django_static_vol:
    driver: local
  db:
    driver: local

services:
  db:
    build:
      context: .
      dockerfile: docker/common/Dockerfile.db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twistdbadmin"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    restart: always
    build:
      context: .
      dockerfile: docker/prod/Dockerfile.celery
    command: celery -A twist worker -l INFO
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy

  django:
    restart: always
    build:
      context: .
      dockerfile: docker/prod/Dockerfile.django
    command: sh -c "./prod_setup.py && gunicorn -w $(($(nproc) + 1)) twist.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - django_static_vol:/twist/static
      - /home/alona/media:/twist/media
      - /home/alona/db_backups:/twist/db_backups
    environment:
      - INIT=false
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  caddy:
    restart: always
    build:
      context: .
      dockerfile: docker/prod/Dockerfile.caddy
    volumes:
      - django_static_vol:/usr/share/caddy/django_static
      - /home/alona/media:/usr/share/caddy/django_media
      - caddy_static_vol:/data
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
