"""Page copy for the singer-tickets guide, keyed by block.

Keys run in page order and match the [nn] markers in the translation export, so a
finished translation drops straight into ``EN``. Values are HTML fragments — inline
``<strong>`` and ``<a>`` are part of the copy, since which words carry the emphasis is a
translation decision, not a layout one. ``{name}`` slots are filled with the URLs from
``views.py`` before rendering.

Both dicts are real copy. When editing one, check whether the other needs the same
change — they are only kept in sync by hand.
"""

HE = {
    'b01': 'אז איך משיגים כרטיס זמר/ת??',
    'b02': 'כרטיסי הזמר/ת נגמרים <strong>ממש מהר</strong>, כי מי לא רוצה להופיע בליווי פסנתר מול הקהל הכי תומך בעולם?',
    'b03': 'אבל יש לנו חדשות טובות בשבילכם:',
    'b04': 'הסיכוי שלכם להשיג כרטיס עלה מאוד לאחרונה!',
    'b05': 'ממש לאחרונה שינינו את השיטה והגבלנו <strong>לכרטיס זמר/ת אחד בכל הזמנה</strong>.',
    'b06': 'אם הגעתם לדף הזה, אתם כבר ביתרון רציני',
    'b07': 'אנחנו חושפים למטה את <strong>כל הטריקים</strong> שקיימים כדי להשיג כרטיס זמר/ת.',
    'b08': 'הצלחתם לקרוא הכל ביסודיות וליישם? כל הכבוד! לא לכל אחד יש את הסבלנות... מה שאומר שיש לכם <strong>יתרון גדול</strong> על כולם!',
    'b09': 'הנה כל מה שצריך לדעת',
    'b10': 'המדריך להשגת כרטיסי זמר/ת בזמן',
    'b11': 'כדי להקל על הביקוש, אנחנו תמיד פותחים את מכירת הכרטיסים לכל התאריכים של החודש <strong>באותו הזמן</strong>',
    'b12': 'אנחנו נותנים התראה יום לפני בקבוצה השקטה, ואז שולחים שם את הלינק ברגע שהמכירה נפתחת.',
    'b13': '<svg class="exp-cta-icon" aria-hidden="true"><use href="#exp-icon-whatsapp"></use></svg> לקבוצה השקטה ←',
    'b14': 'אתם צריכים להיות ממש ״על זה״',
    'b15': 'כרטיסי הזמרים לכל אירועי החודש תמיד אוזלים <strong>תוך פחות מדקה (!!)</strong>. זה אומר שאתם צריכים לחכות ליד הטלפון או המחשב (מה שאתם יותר מהירים איתו) ולהיכנס לאתר ברגע שאנחנו פותחים את המכירה.',
    'b16': 'זה קורה בדרך כלל בין <strong>20:30-20:00</strong>, לרוב קרוב יותר ל<strong>20:00</strong> (תלוי מתי אדם שלנו נרדם 😴) - אלא אם כתבנו אחרת בהודעה בקבוצה.',
    'b17': 'החליטו מראש מה האירוע הראשון שאתם הולכים עליו',
    'b18': 'רוב הסיכויים שתצליחו להשיג כרטיס זמר/ת רק לאחד האירועים, לאור הביקוש הרב. אז ברגע שהמכירה נפתחת, <strong>היכנסו ישר לאירוע המועדף</strong>.',
    'b19': 'מומלץ לפתוח את אתר הכרטיסים מראש',
    'b20': 'אנחנו שולחים בדיוק את <a href="{all_events_url}" target="_blank" rel="noopener noreferrer"><strong>הלינק הזה</strong></a> בקבוצה ברגע שהמכירה נפתחת - אז אפשר להיכנס אליו כבר מראש.',
    'b21': 'בפתיחת המכירה יופיעו האירועים החדשים בהמשך הדף, ממש מעל המפה. משם תגיעו לדף הספציפי של כל אירוע, בו קונים את הכרטיסים.',
    'b22': 'אתר הכרטיסים ←',
    'b23': 'אפשר לרענן את הדף, במקום ללחוץ על הלינק בהודעה',
    'b24': 'אם יש לכם את הסבלנות, אפשר להתחיל לרענן עוד <strong>לפני</strong> שההודעה מגיעה בקבוצה - האמת היא שעוברות מספר שניות בין הרגע שבו התאריכים נוספים לאתר ועד שאנחנו שולחים את ההודעה.',
    'b25': 'אם תתפסו את הרגע הזה - אתם תצליחו לקנות את הכרטיס לפני כולם',
    'b26': 'הכרטיסים יהיו באמת שלכם רק כשתגיעו לשלב הכנסת פרטי האשראי',
    'b27': 'השלב הזה מגיע רק אחרי הכנסת הפרטים האישיים. כלומר, את הפרטים האישיים צריך להכניס <strong>כמה שיותר מהר</strong>, ואת פרטי האשראי תוכלו כבר להכניס ברוגע.',
    'b28': 'הפרטים האישיים',
    'b29': 'מהר!',
    'b30': 'פרטי האשראי',
    'b31': 'ברוגע',
    'b32': 'אם כל הכרטיסים נגמרו לפני שסיימתם להכניס את הפרטים האישיים, אתם תראו הודעת שגיאה ולא תוכלו לעבור הלאה. <br /> (התעלמו מהשעון שאומר שהכרטיסים שמורים במשך 10 דקות - הוא תקף רק אחרי שמגיעים לפרטי האשראי)',
    'b33': 'לא כדאי להוסיף כרטיסי קהל בהזמנה הראשונה',
    'b34': 'זה מבזבז לכם זמן יקר, בדיוק ברגע שבו אתם צריכים להיות <strong>כמה שיותר מהירים</strong>.',
    'b35': '<strong class="exp-quote">״אבל אנחנו רוצים להביא חברים!״</strong> אין בעיה! כרטיסי הקהל נגמרים הרבה יותר לאט. תמיד תוכלו להיכנס מאוחר יותר ולהזמין אותם ברוגע :)',
    'b36': 'לא כדאי לבזבז זמן על התיבה של ״חוגגים משהו אצלנו״',
    'b37': 'בהזמנה של כרטיס זמר/ת <strong>כל שניה קובעת</strong> - אז עדיף פשוט לדלג על התיבה הזאת, שנמצאת באיזור הפרטים האישיים. (זאת התיבה שבה מספרים לנו שחוגגים משהו, ואנחנו דואגים לחגוג אתכם על הבמה)',
    'b38': '<strong class="exp-quote">״אבל אנחנו באמת חוגגים משהו!״ 🎉</strong> אין בעיה! תמיד תוכלו להוסיף את הסיבה לחגיגה שלכם בהזמנה אחרת, או פשוט לשלוח לנו ישירות. רק תגידו לנו את השם של מי שחוגג/ת :)',
    'b39': 'אפשר ״להתאמן״ על התהליך מראש!',
    'b40': 'הכנו לכם במיוחד <a href="{practice_url}" target="_blank" rel="noopener noreferrer"><strong>דף מזויף לגמרי</strong></a>, שעובד בדיוק כמו אירוע אמיתי. תוכלו להתנסות שם במערכת ולראות איך הכל עובד. אין צורך באמת להזמין - החלק הקריטי הוא להבין איך אתם מגיעים כמה שיותר מהר לאיזור של פרטי האשראי.',
    'b41': '<strong>הכי חשוב</strong> - תוכלו להכניס פרטים כך שהדפדפן שלכם כבר <strong>יזכור וימלא את הפרטים באופן אוטומטי</strong>. כל זה מאוד תלוי דפדפן ומכשיר - אז כדאי לנסות כמה פעמים ולוודא שזה עובד לכם.',
    'b42': 'האירוע המזויף לאימון ←',
    'b43': 'שימו לב - זו סימולציה של דף של אירוע ספציפי. כמו שכתוב למעלה, אתם מחכים ומרעננים <a href="{all_events_url}" target="_blank" rel="noopener noreferrer"><strong>באתר הכרטיסים</strong></a> שמרכז את כל האירועים, ורק ברגע שהמכירה נפתחת מתווספים אליו הלינקים לאירועים החדשים (שיראו בדיוק כמו דף הסימולציה).',
    'b44': 'שווה לנסות שוב כמה דקות לאחר המכירה',
    'b45': 'כרטיסים של אנשים שהתחילו להזמין ולא סיימו חוזרים לאתר כעבור 10 דקות - אז ייתכן שיופיעו לאחר מכן כרטיסי זמר/ת פנויים. <strong>יש לכם הזדמנות נוספת!</strong>',
    'b46': 'לא הצלחתם בחודש הזה? אתם לא צריכים לוותר על ערב בלתי נשכח! 🤩',
    'b47': 'גם עם <strong>כרטיס קהל</strong> נהנים בטירוף - שרים מהכיסא, מצטרפים לכל התפקידים בהמילטון יחד עם השכנים, ותופסים את המיקרופון בשירים הקבוצתיים 🎤🎤',
    'b48': 'ואפילו יש 2 דרכים לעלות לבמה!',
    'b49': '<span class="exp-fallback-star-emoji" aria-hidden="true">🎲</span> <span><strong>ההגרלה</strong> בזמן האירוע - הזוכים מבצעים שיר על הבמה!</span>',
    'b50': '<span class="exp-fallback-star-emoji exp-fallback-star-emoji--tight" aria-hidden="true">🎤</span> <span><strong>דואט</strong> - אפשר להצטרף לשיר של אחד הזמרים!</span>',
    'b51': 'כרטיסי הקהל אוזלים יותר לאט (אבל לא היינו מתעכבים יותר מדי..)',
    'b52': 'קניית כרטיסים ברגע האחרון!',
    'b53': 'אנשים לפעמים מוכרים כרטיסי זמר/ת ממש ברגע האחרון (לפעמים אפילו שעות לפני) בקבוצת הקהילה שלנו.',
    'b54': 'הקבוצה הזאת מאוד פעילה וכיפית, ומדברים שם כל הזמן על כל מה שקשור לאירועים שלנו ולברודווי ודיסני באופן כללי.',
    'b55': '<svg class="exp-cta-icon" aria-hidden="true"><use href="#exp-icon-whatsapp"></use></svg> לקבוצת הקהילה ←',
    'b56': 'אנחנו מבקשים ממי שמוכר כרטיס זמר/ת לשים את האימוג׳י 🎙️ כדי שיהיה יותר קל לשים לב למכירה בין כל ההודעות.',
    'b57': 'בהצלחה, ונתראה בקרוב! 🤞',
    'b58': 'שני ואלון 🎤🎹',
    # Screen-reader description of the checkout-flow diagram.
    'b59': 'קודם פרטים אישיים - מהר. אחר כך פרטי אשראי - ברוגע',
}

EN = {
    'b01': 'So how do you get a singer ticket??',
    'b02': "Singer tickets run out <strong>really fast</strong> - because who wouldn't want to perform to piano accompaniment in front of the most supportive audience in the world?",
    'b03': 'But we have good news for you:',
    'b04': 'Your chances of getting a ticket just went way up!',
    'b05': 'We recently changed the system and limited it to <strong>one singer ticket per order</strong>.',
    'b06': "If you made it to this page, you're already ahead of the game",
    'b07': "Below we're revealing <strong>all the tricks</strong> there are for getting a singer ticket.",
    'b08': 'Managed to read everything thoroughly and apply it? Well done! Not everyone has the patience... which means you have a serious <strong>edge</strong> over everyone else!',
    'b09': "Here's everything you need to know",
    'b10': 'The guide to getting singer tickets in time',
    'b11': "To ease the demand, we always open ticket sales for all of the month's dates <strong>at the same time</strong>",
    'b12': 'We give a heads-up in the silent WhatsApp group a day before, and then send the link there the moment the sale opens.',
    'b13': '<svg class="exp-cta-icon" aria-hidden="true"><use href="#exp-icon-whatsapp"></use></svg> To the silent WhatsApp group ←',
    'b14': 'You really need to be "on"',
    'b15': "Singer tickets for all of the month's events always run out <strong>in less than a minute (!!)</strong>. That means you need to wait next to the phone or computer (whichever you use faster) and enter the site the moment we open the sale.",
    'b16': 'This usually happens between <strong>20:00-20:30</strong>, most often closer to <strong>20:00</strong> (depends on when our Adam falls asleep 😴) - unless we said otherwise in the group message.',
    'b17': "Decide ahead of time which event you're going for first",
    'b18': "Odds are you'll only manage to get a singer ticket for one of the events, given the high demand. So the moment the sale opens, <strong>go straight to your preferred event</strong>.",
    'b19': 'We recommend opening the ticket site ahead of time',
    'b20': 'We send exactly <a href="{all_events_url}" target="_blank" rel="noopener noreferrer"><strong>this link</strong></a> in the group the moment the sale opens - so you can already enter it ahead of time.',
    'b21': "When the sale opens, the new events will appear further down the page, right above the map. From there you'll get to each event's specific page, where you buy the tickets.",
    'b22': 'The ticket site ←',
    'b23': 'You can refresh the page, instead of clicking the link in the message',
    'b24': 'If you have the patience, you can start refreshing even <strong>before</strong> the message arrives in the group - the truth is that a few seconds pass between the moment the dates are added to the site and when we send the message.',
    'b25': "If you manage to catch that moment - you'll buy your ticket before everyone else",
    'b26': 'The tickets will really be yours only once you get to the credit card details stage',
    'b27': 'This stage comes only after entering your personal details. That is, you need to enter your personal details <strong>as fast as possible</strong>, and then you can take your time with the credit card details.',
    'b28': 'Personal details',
    'b29': 'Fast!',
    'b30': 'Credit card details',
    'b31': 'Take your time',
    'b32': "If all the tickets run out before you finish entering your personal details, you'll get an error message and won't be able to continue. <br /> (Ignore the timer that says your tickets are saved for 10 minutes - it only applies once you've reached the credit card details)",
    'b33': "Don't add audience tickets to your first order",
    'b34': 'It wastes precious time, exactly when you need to be <strong>as fast as possible</strong>.',
    'b35': '<strong class="exp-quote">"But we want to bring friends!"</strong> No problem! Audience tickets run out much more slowly. You can always come back later and order them at your own pace :)',
    'b36': 'Don\'t waste time on the "Celebrating something with us" box',
    'b37': "When ordering a singer ticket <strong>every second counts</strong> - so it's best to just skip this box, which is in the personal details area. (That's the box where you tell us you're celebrating something, and we make sure to celebrate you on stage)",
    'b38': '<strong class="exp-quote">"But we really are celebrating something!" 🎉</strong> No problem! You can always add the reason for your celebration in another order, or just send it to us directly. Just tell us the name of whoever\'s celebrating :)',
    'b39': 'You can "practice" the process ahead of time!',
    'b40': 'We prepared a <a href="{practice_url}" target="_blank" rel="noopener noreferrer"><strong>completely fake page</strong></a> especially for you, which works exactly like a real event. You can try out the system there and see how it all works. There\'s no need to actually order - the critical part is figuring out how to reach the credit card details area as fast as you can.',
    'b41': "<strong>Most importantly</strong> - you can enter your details so your browser will already <strong>remember and fill them in automatically</strong>. All of this depends a lot on the browser and device - so it's worth trying a few times and making sure it works for you.",
    'b42': 'The fake practice event ←',
    'b43': 'Note - this is a simulation of a specific event\'s page. As mentioned above, you wait and refresh on <a href="{all_events_url}" target="_blank" rel="noopener noreferrer"><strong>the ticket site</strong></a> that lists all the events, and only when the sale opens are the links to the new events added to it (they\'ll look exactly like the simulation page).',
    'b44': "It's worth trying again a few minutes after the sale",
    'b45': "Tickets of people who started ordering and didn't finish return to the site after 10 minutes - so free singer tickets might appear afterwards. <strong>You have another chance!</strong>",
    'b46': "Didn't get it this month? You don't have to give up on an unforgettable night! 🤩",
    'b47': "With an <strong>audience ticket</strong> you'll have an incredible time as well - singing from your seat, joining in all the parts in Hamilton with your neighbors, and grabbing the mic during the group songs 🎤🎤",
    'b48': 'And there are even 2 ways to get up on stage!',
    'b49': '<span class="exp-fallback-star-emoji" aria-hidden="true">🎲</span> <span><strong>The raffle</strong> during the event - winners perform a song on stage!</span>',
    'b50': '<span class="exp-fallback-star-emoji exp-fallback-star-emoji--tight" aria-hidden="true">🎤</span> <span><strong>Duet</strong> - you can join one of the singers\' songs!</span>',
    'b51': "Audience tickets run out more slowly (but we wouldn't wait too long..)",
    'b52': 'Buying tickets at the last minute!',
    'b53': 'People sometimes sell singer tickets at the very last minute (sometimes even hours before) in our community group.',
    'b54': 'This is a super fun and active group - with people constantly chatting about our events, and about Broadway and Disney in general.',
    'b55': '<svg class="exp-cta-icon" aria-hidden="true"><use href="#exp-icon-whatsapp"></use></svg> To the community group ←',
    'b56': "We ask whoever's selling a singer ticket to add the 🎙️ emoji, so it's easier to notice the sale among all the messages.",
    'b57': 'Good luck, and see you soon! 🤞',
    'b58': 'Shani and Alon 🎤🎹',
    'b59': 'First personal details - fast. Then credit card details - take your time',
}

STRINGS = {'he': HE, 'en': EN}
