--
-- PostgreSQL database dump
--

-- Dumped from database version 12.11 (Ubuntu 12.11-0ubuntu0.20.04.1)
-- Dumped by pg_dump version 12.11 (Ubuntu 12.11-0ubuntu0.20.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public.song_signup_songrequest_additional_singers DROP CONSTRAINT song_signup_songrequ_songrequest_id_2e38e58b_fk_song_sign;
ALTER TABLE ONLY public.song_signup_songrequest DROP CONSTRAINT song_signup_songrequ_singer_id_d2a4ad82_fk_song_sign;
ALTER TABLE ONLY public.song_signup_songrequest_additional_singers DROP CONSTRAINT song_signup_songrequ_singer_id_a529a8f4_fk_song_sign;
ALTER TABLE ONLY public.song_signup_songrequest DROP CONSTRAINT song_signup_songrequ_duet_partner_id_5dad5c17_fk_song_sign;
ALTER TABLE ONLY public.song_signup_singer_user_permissions DROP CONSTRAINT song_signup_singer_u_singer_id_20ebc8cd_fk_song_sign;
ALTER TABLE ONLY public.song_signup_singer_user_permissions DROP CONSTRAINT song_signup_singer_u_permission_id_94d0d848_fk_auth_perm;
ALTER TABLE ONLY public.song_signup_singer_groups DROP CONSTRAINT song_signup_singer_groups_group_id_dd867d90_fk_auth_group_id;
ALTER TABLE ONLY public.song_signup_singer_groups DROP CONSTRAINT song_signup_singer_g_singer_id_2c98845b_fk_song_sign;
ALTER TABLE ONLY public.song_signup_groupsongrequest DROP CONSTRAINT song_signup_groupson_requested_by_id_28ee6931_fk_song_sign;
ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_user_id_c564eba6_fk_song_signup_singer_id;
ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co;
ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm;
DROP INDEX public.song_signup_songrequest_singer_id_d2a4ad82;
DROP INDEX public.song_signup_songrequest_duet_partner_id_5dad5c17;
DROP INDEX public.song_signup_songrequest_additional_singers_singer_id_a529a8f4;
DROP INDEX public.song_signup_songrequest_ad_songrequest_id_2e38e58b;
DROP INDEX public.song_signup_singer_username_b362f1d1_like;
DROP INDEX public.song_signup_singer_user_permissions_singer_id_20ebc8cd;
DROP INDEX public.song_signup_singer_user_permissions_permission_id_94d0d848;
DROP INDEX public.song_signup_singer_groups_singer_id_2c98845b;
DROP INDEX public.song_signup_singer_groups_group_id_dd867d90;
DROP INDEX public.song_signup_groupsongrequest_requested_by_id_28ee6931;
DROP INDEX public.django_session_session_key_c0390e0f_like;
DROP INDEX public.django_session_expire_date_a5c62663;
DROP INDEX public.django_admin_log_user_id_c564eba6;
DROP INDEX public.django_admin_log_content_type_id_c4bce8eb;
DROP INDEX public.auth_permission_content_type_id_2f476e4b;
DROP INDEX public.auth_group_permissions_permission_id_84c5c92e;
DROP INDEX public.auth_group_permissions_group_id_b120cbf9;
DROP INDEX public.auth_group_name_a6ea08ec_like;
ALTER TABLE ONLY public.song_signup_songrequest DROP CONSTRAINT song_signup_songrequest_song_name_musical_singer_d2c870a5_uniq;
ALTER TABLE ONLY public.song_signup_songrequest DROP CONSTRAINT song_signup_songrequest_pkey;
ALTER TABLE ONLY public.song_signup_songrequest_additional_singers DROP CONSTRAINT song_signup_songrequest_additional_singers_pkey;
ALTER TABLE ONLY public.song_signup_songrequest_additional_singers DROP CONSTRAINT song_signup_songrequest__songrequest_id_singer_id_1b295821_uniq;
ALTER TABLE ONLY public.song_signup_singer DROP CONSTRAINT song_signup_singer_username_key;
ALTER TABLE ONLY public.song_signup_singer_user_permissions DROP CONSTRAINT song_signup_singer_user_permissions_pkey;
ALTER TABLE ONLY public.song_signup_singer_user_permissions DROP CONSTRAINT song_signup_singer_user__singer_id_permission_id_d96a7da1_uniq;
ALTER TABLE ONLY public.song_signup_singer DROP CONSTRAINT song_signup_singer_pkey;
ALTER TABLE ONLY public.song_signup_singer_groups DROP CONSTRAINT song_signup_singer_groups_singer_id_group_id_0c2bce52_uniq;
ALTER TABLE ONLY public.song_signup_singer_groups DROP CONSTRAINT song_signup_singer_groups_pkey;
ALTER TABLE ONLY public.song_signup_groupsongrequest DROP CONSTRAINT song_signup_groupsongrequest_pkey;
ALTER TABLE ONLY public.flags_flagstate DROP CONSTRAINT flags_flagstate_pkey;
ALTER TABLE ONLY public.flags_flagstate DROP CONSTRAINT flags_flagstate_name_condition_value_4e81ec48_uniq;
ALTER TABLE ONLY public.django_session DROP CONSTRAINT django_session_pkey;
ALTER TABLE ONLY public.django_migrations DROP CONSTRAINT django_migrations_pkey;
ALTER TABLE ONLY public.django_content_type DROP CONSTRAINT django_content_type_pkey;
ALTER TABLE ONLY public.django_content_type DROP CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq;
ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_pkey;
ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_pkey;
ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq;
ALTER TABLE ONLY public.auth_group DROP CONSTRAINT auth_group_pkey;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_pkey;
ALTER TABLE ONLY public.auth_group_permissions DROP CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq;
ALTER TABLE ONLY public.auth_group DROP CONSTRAINT auth_group_name_key;
ALTER TABLE public.song_signup_songrequest_additional_singers ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.song_signup_songrequest ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.song_signup_singer_user_permissions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.song_signup_singer_groups ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.song_signup_singer ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.song_signup_groupsongrequest ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.flags_flagstate ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_migrations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_content_type ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.django_admin_log ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_permission ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_group_permissions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE public.auth_group ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE public.song_signup_songrequest_id_seq;
DROP SEQUENCE public.song_signup_songrequest_additional_singers_id_seq;
DROP TABLE public.song_signup_songrequest_additional_singers;
DROP TABLE public.song_signup_songrequest;
DROP SEQUENCE public.song_signup_singer_user_permissions_id_seq;
DROP TABLE public.song_signup_singer_user_permissions;
DROP SEQUENCE public.song_signup_singer_id_seq;
DROP SEQUENCE public.song_signup_singer_groups_id_seq;
DROP TABLE public.song_signup_singer_groups;
DROP TABLE public.song_signup_singer;
DROP SEQUENCE public.song_signup_groupsongrequest_id_seq;
DROP TABLE public.song_signup_groupsongrequest;
DROP SEQUENCE public.flags_flagstate_id_seq;
DROP TABLE public.flags_flagstate;
DROP TABLE public.django_session;
DROP SEQUENCE public.django_migrations_id_seq;
DROP TABLE public.django_migrations;
DROP SEQUENCE public.django_content_type_id_seq;
DROP TABLE public.django_content_type;
DROP SEQUENCE public.django_admin_log_id_seq;
DROP TABLE public.django_admin_log;
DROP SEQUENCE public.auth_permission_id_seq;
DROP TABLE public.auth_permission;
DROP SEQUENCE public.auth_group_permissions_id_seq;
DROP TABLE public.auth_group_permissions;
DROP SEQUENCE public.auth_group_id_seq;
DROP TABLE public.auth_group;
DROP EXTENSION citext;
--
-- Name: citext; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


--
-- Name: EXTENSION citext; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: twistdbadmin
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO twistdbadmin;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: twistdbadmin
--

CREATE SEQUENCE public.auth_group_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_group_id_seq OWNER TO twistdbadmin;

--
-- Name: auth_group_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: twistdbadmin
--

ALTER SEQUENCE public.auth_group_id_seq OWNED BY public.auth_group.id;


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: twistdbadmin
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO twistdbadmin;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: twistdbadmin
--

CREATE SEQUENCE public.auth_group_permissions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_group_permissions_id_seq OWNER TO twistdbadmin;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: twistdbadmin
--

ALTER SEQUENCE public.auth_group_permissions_id_seq OWNED BY public.auth_group_permissions.id;


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: twistdbadmin
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO twistdbadmin;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: twistdbadmin
--

CREATE SEQUENCE public.auth_permission_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_permission_id_seq OWNER TO twistdbadmin;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: twistdbadmin
--

ALTER SEQUENCE public.auth_permission_id_seq OWNED BY public.auth_permission.id;


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: twistdbadmin
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO twistdbadmin;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: twistdbadmin
--

CREATE SEQUENCE public.django_admin_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_admin_log_id_seq OWNER TO twistdbadmin;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: twistdbadmin
--

ALTER SEQUENCE public.django_admin_log_id_seq OWNED BY public.django_admin_log.id;


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: twistdbadmin
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO twistdbadmin;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: twistdbadmin
--

CREATE SEQUENCE public.django_content_type_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_content_type_id_seq OWNER TO twistdbadmin;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: twistdbadmin
--

ALTER SEQUENCE public.django_content_type_id_seq OWNED BY public.django_content_type.id;


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: twistdbadmin
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO twistdbadmin;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: twistdbadmin
--

CREATE SEQUENCE public.django_migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_migrations_id_seq OWNER TO twistdbadmin;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: twistdbadmin
--

ALTER SEQUENCE public.django_migrations_id_seq OWNED BY public.django_migrations.id;


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: twistdbadmin
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO twistdbadmin;

--
-- Name: flags_flagstate; Type: TABLE; Schema: public; Owner: twistdbadmin
--

CREATE TABLE public.flags_flagstate (
    id integer NOT NULL,
    name character varying(64) NOT NULL,
    condition character varying(64) NOT NULL,
    value character varying(127) NOT NULL,
    required boolean NOT NULL
);


ALTER TABLE public.flags_flagstate OWNER TO twistdbadmin;

--
-- Name: flags_flagstate_id_seq; Type: SEQUENCE; Schema: public; Owner: twistdbadmin
--

CREATE SEQUENCE public.flags_flagstate_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.flags_flagstate_id_seq OWNER TO twistdbadmin;

--
-- Name: flags_flagstate_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: twistdbadmin
--

ALTER SEQUENCE public.flags_flagstate_id_seq OWNED BY public.flags_flagstate.id;


--
-- Name: song_signup_groupsongrequest; Type: TABLE; Schema: public; Owner: twistdbadmin
--

CREATE TABLE public.song_signup_groupsongrequest (
    id integer NOT NULL,
    song_name public.citext NOT NULL,
    musical public.citext NOT NULL,
    request_time timestamp with time zone NOT NULL,
    requested_by_id integer NOT NULL
);


ALTER TABLE public.song_signup_groupsongrequest OWNER TO twistdbadmin;

--
-- Name: song_signup_groupsongrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: twistdbadmin
--

CREATE SEQUENCE public.song_signup_groupsongrequest_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.song_signup_groupsongrequest_id_seq OWNER TO twistdbadmin;

--
-- Name: song_signup_groupsongrequest_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: twistdbadmin
--

ALTER SEQUENCE public.song_signup_groupsongrequest_id_seq OWNED BY public.song_signup_groupsongrequest.id;


--
-- Name: song_signup_singer; Type: TABLE; Schema: public; Owner: twistdbadmin
--

CREATE TABLE public.song_signup_singer (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    cy1_position integer,
    no_image_upload boolean NOT NULL,
    cy2_position integer,
    cy3_position integer,
    lscy_position integer,
    placeholder boolean NOT NULL
);


ALTER TABLE public.song_signup_singer OWNER TO twistdbadmin;

--
-- Name: song_signup_singer_groups; Type: TABLE; Schema: public; Owner: twistdbadmin
--

CREATE TABLE public.song_signup_singer_groups (
    id integer NOT NULL,
    singer_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.song_signup_singer_groups OWNER TO twistdbadmin;

--
-- Name: song_signup_singer_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: twistdbadmin
--

CREATE SEQUENCE public.song_signup_singer_groups_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.song_signup_singer_groups_id_seq OWNER TO twistdbadmin;

--
-- Name: song_signup_singer_groups_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: twistdbadmin
--

ALTER SEQUENCE public.song_signup_singer_groups_id_seq OWNED BY public.song_signup_singer_groups.id;


--
-- Name: song_signup_singer_id_seq; Type: SEQUENCE; Schema: public; Owner: twistdbadmin
--

CREATE SEQUENCE public.song_signup_singer_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.song_signup_singer_id_seq OWNER TO twistdbadmin;

--
-- Name: song_signup_singer_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: twistdbadmin
--

ALTER SEQUENCE public.song_signup_singer_id_seq OWNED BY public.song_signup_singer.id;


--
-- Name: song_signup_singer_user_permissions; Type: TABLE; Schema: public; Owner: twistdbadmin
--

CREATE TABLE public.song_signup_singer_user_permissions (
    id integer NOT NULL,
    singer_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.song_signup_singer_user_permissions OWNER TO twistdbadmin;

--
-- Name: song_signup_singer_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: twistdbadmin
--

CREATE SEQUENCE public.song_signup_singer_user_permissions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.song_signup_singer_user_permissions_id_seq OWNER TO twistdbadmin;

--
-- Name: song_signup_singer_user_permissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: twistdbadmin
--

ALTER SEQUENCE public.song_signup_singer_user_permissions_id_seq OWNED BY public.song_signup_singer_user_permissions.id;


--
-- Name: song_signup_songrequest; Type: TABLE; Schema: public; Owner: twistdbadmin
--

CREATE TABLE public.song_signup_songrequest (
    id integer NOT NULL,
    song_name public.citext NOT NULL,
    musical public.citext NOT NULL,
    request_time timestamp with time zone NOT NULL,
    performance_time timestamp with time zone,
    singer_id integer NOT NULL,
    priority integer,
    "position" integer,
    duet_partner_id integer,
    cycle double precision,
    placeholder boolean NOT NULL
);


ALTER TABLE public.song_signup_songrequest OWNER TO twistdbadmin;

--
-- Name: song_signup_songrequest_additional_singers; Type: TABLE; Schema: public; Owner: twistdbadmin
--

CREATE TABLE public.song_signup_songrequest_additional_singers (
    id integer NOT NULL,
    songrequest_id integer NOT NULL,
    singer_id integer NOT NULL
);


ALTER TABLE public.song_signup_songrequest_additional_singers OWNER TO twistdbadmin;

--
-- Name: song_signup_songrequest_additional_singers_id_seq; Type: SEQUENCE; Schema: public; Owner: twistdbadmin
--

CREATE SEQUENCE public.song_signup_songrequest_additional_singers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.song_signup_songrequest_additional_singers_id_seq OWNER TO twistdbadmin;

--
-- Name: song_signup_songrequest_additional_singers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: twistdbadmin
--

ALTER SEQUENCE public.song_signup_songrequest_additional_singers_id_seq OWNED BY public.song_signup_songrequest_additional_singers.id;


--
-- Name: song_signup_songrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: twistdbadmin
--

CREATE SEQUENCE public.song_signup_songrequest_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.song_signup_songrequest_id_seq OWNER TO twistdbadmin;

--
-- Name: song_signup_songrequest_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: twistdbadmin
--

ALTER SEQUENCE public.song_signup_songrequest_id_seq OWNED BY public.song_signup_songrequest.id;


--
-- Name: auth_group id; Type: DEFAULT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.auth_group ALTER COLUMN id SET DEFAULT nextval('public.auth_group_id_seq'::regclass);


--
-- Name: auth_group_permissions id; Type: DEFAULT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.auth_group_permissions ALTER COLUMN id SET DEFAULT nextval('public.auth_group_permissions_id_seq'::regclass);


--
-- Name: auth_permission id; Type: DEFAULT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.auth_permission ALTER COLUMN id SET DEFAULT nextval('public.auth_permission_id_seq'::regclass);


--
-- Name: django_admin_log id; Type: DEFAULT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.django_admin_log ALTER COLUMN id SET DEFAULT nextval('public.django_admin_log_id_seq'::regclass);


--
-- Name: django_content_type id; Type: DEFAULT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.django_content_type ALTER COLUMN id SET DEFAULT nextval('public.django_content_type_id_seq'::regclass);


--
-- Name: django_migrations id; Type: DEFAULT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.django_migrations ALTER COLUMN id SET DEFAULT nextval('public.django_migrations_id_seq'::regclass);


--
-- Name: flags_flagstate id; Type: DEFAULT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.flags_flagstate ALTER COLUMN id SET DEFAULT nextval('public.flags_flagstate_id_seq'::regclass);


--
-- Name: song_signup_groupsongrequest id; Type: DEFAULT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_groupsongrequest ALTER COLUMN id SET DEFAULT nextval('public.song_signup_groupsongrequest_id_seq'::regclass);


--
-- Name: song_signup_singer id; Type: DEFAULT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_singer ALTER COLUMN id SET DEFAULT nextval('public.song_signup_singer_id_seq'::regclass);


--
-- Name: song_signup_singer_groups id; Type: DEFAULT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_singer_groups ALTER COLUMN id SET DEFAULT nextval('public.song_signup_singer_groups_id_seq'::regclass);


--
-- Name: song_signup_singer_user_permissions id; Type: DEFAULT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_singer_user_permissions ALTER COLUMN id SET DEFAULT nextval('public.song_signup_singer_user_permissions_id_seq'::regclass);


--
-- Name: song_signup_songrequest id; Type: DEFAULT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_songrequest ALTER COLUMN id SET DEFAULT nextval('public.song_signup_songrequest_id_seq'::regclass);


--
-- Name: song_signup_songrequest_additional_singers id; Type: DEFAULT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_songrequest_additional_singers ALTER COLUMN id SET DEFAULT nextval('public.song_signup_songrequest_additional_singers_id_seq'::regclass);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: twistdbadmin
--

COPY public.auth_group (id, name) FROM stdin;
1	singers
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: twistdbadmin
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
2	1	32
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: twistdbadmin
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Singer	6	add_singer
22	Can change Singer	6	change_singer
23	Can delete Singer	6	delete_singer
24	Can view Singer	6	view_singer
25	Can add group song request	7	add_groupsongrequest
26	Can change group song request	7	change_groupsongrequest
27	Can delete group song request	7	delete_groupsongrequest
28	Can view group song request	7	view_groupsongrequest
29	Can add song request	8	add_songrequest
30	Can change song request	8	change_songrequest
31	Can delete song request	8	delete_songrequest
32	Can view song request	8	view_songrequest
33	Can add flag state	9	add_flagstate
34	Can change flag state	9	change_flagstate
35	Can delete flag state	9	delete_flagstate
36	Can view flag state	9	view_flagstate
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: twistdbadmin
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2022-06-02 13:33:06.948665+00	2	Shani Wahrman	1	[{"added": {}}]	6	1
2	2022-06-02 13:35:26.661644+00	3	Uriel Rosenzweig	1	[{"added": {}}]	6	1
3	2022-06-02 13:36:43.865423+00	1	Alon Aviv	2	[{"changed": {"fields": ["First name", "Last name"]}}]	6	1
4	2022-06-02 13:37:20.341053+00	1	singers	1	[{"added": {}}]	3	1
5	2022-06-02 15:48:27.761363+00	1	singers	2	[{"changed": {"fields": ["Permissions"]}}]	3	1
6	2022-06-02 16:37:05.427818+00	2	Shani Wahrman	2	[{"changed": {"fields": ["Password"]}}]	6	1
7	2022-06-02 17:24:15.477964+00	2	GroupSongRequest object (2)	3		7	1
8	2022-06-02 18:53:02.174231+00	6	GroupSongRequest object (6)	3		7	1
9	2022-06-02 18:53:11.123124+00	9	GroupSongRequest object (9)	3		7	1
10	2022-06-02 18:53:11.125586+00	10	GroupSongRequest object (10)	3		7	1
11	2022-06-17 13:19:26.564721+00	3	GroupSongRequest object (3)	3		7	1
12	2022-06-17 13:19:36.000364+00	12	GroupSongRequest object (12)	3		7	1
13	2022-06-17 13:19:36.002877+00	7	GroupSongRequest object (7)	3		7	1
14	2022-06-17 13:19:36.004533+00	11	GroupSongRequest object (11)	3		7	1
15	2022-06-17 13:19:36.006186+00	4	GroupSongRequest object (4)	3		7	1
16	2022-06-17 13:19:36.007569+00	8	GroupSongRequest object (8)	3		7	1
17	2022-06-17 13:19:36.00897+00	5	GroupSongRequest object (5)	3		7	1
18	2022-06-17 13:23:13.658782+00	13	GroupSongRequest object (13)	1	[{"added": {}}]	7	1
19	2022-06-17 13:23:37.171737+00	14	GroupSongRequest object (14)	1	[{"added": {}}]	7	1
20	2022-06-17 13:23:55.526342+00	15	GroupSongRequest object (15)	1	[{"added": {}}]	7	1
21	2022-06-17 13:24:08.638299+00	16	GroupSongRequest object (16)	1	[{"added": {}}]	7	1
22	2022-06-17 13:36:17.5688+00	17	GroupSongRequest object (17)	1	[{"added": {}}]	7	1
23	2022-06-17 13:36:32.238818+00	18	GroupSongRequest object (18)	1	[{"added": {}}]	7	1
24	2022-06-17 13:36:32.252686+00	19	GroupSongRequest object (19)	1	[{"added": {}}]	7	1
25	2022-06-17 13:36:32.750753+00	20	GroupSongRequest object (20)	1	[{"added": {}}]	7	1
26	2022-06-17 13:36:50.065128+00	18	GroupSongRequest object (18)	3		7	1
27	2022-06-17 13:36:50.067227+00	19	GroupSongRequest object (19)	3		7	1
28	2022-06-17 13:36:50.068888+00	20	GroupSongRequest object (20)	3		7	1
29	2022-06-17 13:37:08.92937+00	21	GroupSongRequest object (21)	1	[{"added": {}}]	7	1
30	2022-06-17 13:38:41.732489+00	22	GroupSongRequest object (22)	1	[{"added": {}}]	7	1
31	2022-06-17 13:44:32.484292+00	23	GroupSongRequest object (23)	1	[{"added": {}}]	7	1
32	2022-06-17 13:45:15.462694+00	24	GroupSongRequest object (24)	1	[{"added": {}}]	7	1
33	2022-06-17 13:49:31.847336+00	25	GroupSongRequest object (25)	1	[{"added": {}}]	7	1
34	2022-06-17 13:50:16.929426+00	26	GroupSongRequest object (26)	1	[{"added": {}}]	7	1
35	2022-06-17 13:50:58.354784+00	27	GroupSongRequest object (27)	1	[{"added": {}}]	7	1
36	2022-06-17 13:53:20.493506+00	28	GroupSongRequest object (28)	1	[{"added": {}}]	7	1
37	2022-06-17 13:54:46.47928+00	29	GroupSongRequest object (29)	1	[{"added": {}}]	7	1
38	2022-06-17 13:55:48.870402+00	30	GroupSongRequest object (30)	1	[{"added": {}}]	7	1
39	2022-06-17 13:57:04.371802+00	31	GroupSongRequest object (31)	1	[{"added": {}}]	7	1
40	2022-06-17 13:58:23.008663+00	32	GroupSongRequest object (32)	1	[{"added": {}}]	7	1
41	2022-06-17 13:59:51.091839+00	33	GroupSongRequest object (33)	1	[{"added": {}}]	7	1
42	2022-06-17 14:05:29.838155+00	34	GroupSongRequest object (34)	1	[{"added": {}}]	7	1
43	2022-06-17 14:10:53.802272+00	35	GroupSongRequest object (35)	1	[{"added": {}}]	7	1
44	2022-06-17 14:11:17.397138+00	36	GroupSongRequest object (36)	1	[{"added": {}}]	7	1
45	2022-06-17 14:11:38.896652+00	37	GroupSongRequest object (37)	1	[{"added": {}}]	7	1
46	2022-06-17 14:12:11.93008+00	38	GroupSongRequest object (38)	1	[{"added": {}}]	7	1
47	2022-06-17 14:12:29.75011+00	39	GroupSongRequest object (39)	1	[{"added": {}}]	7	1
48	2022-06-17 14:13:06.444135+00	39	GroupSongRequest object (39)	2	[{"changed": {"fields": ["Song name"]}}]	7	1
49	2022-06-17 14:14:41.864179+00	40	GroupSongRequest object (40)	1	[{"added": {}}]	7	1
50	2022-06-17 14:17:30.698327+00	41	GroupSongRequest object (41)	1	[{"added": {}}]	7	1
51	2022-06-17 14:17:53.233771+00	42	GroupSongRequest object (42)	1	[{"added": {}}]	7	1
52	2022-06-17 14:18:13.163693+00	43	GroupSongRequest object (43)	1	[{"added": {}}]	7	1
53	2022-06-17 14:19:37.045161+00	44	GroupSongRequest object (44)	1	[{"added": {}}]	7	1
54	2022-06-17 14:20:02.740349+00	45	GroupSongRequest object (45)	1	[{"added": {}}]	7	1
55	2022-06-17 14:23:02.864933+00	46	GroupSongRequest object (46)	1	[{"added": {}}]	7	1
56	2022-06-17 14:29:27.180429+00	47	GroupSongRequest object (47)	1	[{"added": {}}]	7	1
57	2022-06-17 14:31:37.731248+00	48	GroupSongRequest object (48)	1	[{"added": {}}]	7	1
58	2022-06-17 14:32:37.502971+00	49	GroupSongRequest object (49)	1	[{"added": {}}]	7	1
59	2022-06-17 14:34:49.615318+00	50	GroupSongRequest object (50)	1	[{"added": {}}]	7	1
60	2022-06-17 15:01:05.603141+00	51	GroupSongRequest object (51)	1	[{"added": {}}]	7	1
61	2022-06-21 05:09:24.305304+00	52	GroupSongRequest object (52)	3		7	1
62	2022-06-21 05:09:24.307707+00	53	GroupSongRequest object (53)	3		7	1
63	2022-06-21 05:09:24.309308+00	54	GroupSongRequest object (54)	3		7	1
64	2022-06-21 05:09:24.311054+00	55	GroupSongRequest object (55)	3		7	1
65	2022-06-21 05:09:24.312582+00	56	GroupSongRequest object (56)	3		7	1
66	2022-06-21 05:09:50.015281+00	61	GroupSongRequest object (61)	1	[{"added": {}}]	7	1
67	2022-06-21 05:10:11.450676+00	62	GroupSongRequest object (62)	1	[{"added": {}}]	7	1
68	2022-06-21 05:11:02.120069+00	63	GroupSongRequest object (63)	1	[{"added": {}}]	7	1
69	2022-06-22 22:43:51.719316+00	1	CAN_SIGNUP is enabled when boolean is False	2	[]	9	1
70	2022-07-05 12:53:12.10568+00	2	Shani Wahrman	2	[{"changed": {"fields": ["Staff status"]}}]	6	1
71	2022-07-05 12:54:21.421065+00	2	Shani Wahrman	3		6	1
72	2022-07-05 12:54:52.529897+00	70	Shani Wahrman	1	[{"added": {}}]	6	1
73	2022-07-05 12:56:21.61297+00	70	Shani Wahrman	3		6	1
74	2022-07-05 12:56:41.642635+00	3	Uriel Rosenzweig	3		6	1
75	2022-07-05 12:58:00.532885+00	71	Shani Wahrman	2	[{"changed": {"fields": ["First name", "Last name"]}}]	6	1
76	2022-07-05 15:15:48.361218+00	64	GroupSongRequest object (64)	1	[{"added": {}}]	7	71
77	2022-07-21 08:46:47.418536+00	66	GroupSongRequest object (66)	1	[{"added": {}}]	7	71
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: twistdbadmin
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	song_signup	singer
7	song_signup	groupsongrequest
8	song_signup	songrequest
9	flags	flagstate
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: twistdbadmin
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2022-06-02 13:30:37.29094+00
2	contenttypes	0002_remove_content_type_name	2022-06-02 13:30:37.298652+00
3	auth	0001_initial	2022-06-02 13:30:37.351582+00
4	auth	0002_alter_permission_name_max_length	2022-06-02 13:30:37.366064+00
5	auth	0003_alter_user_email_max_length	2022-06-02 13:30:37.375912+00
6	auth	0004_alter_user_username_opts	2022-06-02 13:30:37.383992+00
7	auth	0005_alter_user_last_login_null	2022-06-02 13:30:37.389985+00
8	auth	0006_require_contenttypes_0002	2022-06-02 13:30:37.391911+00
9	auth	0007_alter_validators_add_error_messages	2022-06-02 13:30:37.398045+00
10	auth	0008_alter_user_username_max_length	2022-06-02 13:30:37.403986+00
11	auth	0009_alter_user_last_name_max_length	2022-06-02 13:30:37.409864+00
12	auth	0010_alter_group_name_max_length	2022-06-02 13:30:37.416293+00
13	auth	0011_update_proxy_permissions	2022-06-02 13:30:37.42239+00
14	auth	0012_alter_user_first_name_max_length	2022-06-02 13:30:37.428316+00
15	song_signup	0001_initial	2022-06-02 13:31:04.942291+00
16	admin	0001_initial	2022-06-02 13:31:04.968168+00
17	admin	0002_logentry_remove_auto_add	2022-06-02 13:31:04.978932+00
18	admin	0003_logentry_add_action_flag_choices	2022-06-02 13:31:04.989365+00
19	flags	0001_initial	2022-06-02 13:31:05.000794+00
20	flags	0002_auto_20151030_1401	2022-06-02 13:31:05.002095+00
21	flags	0003_flag_hidden	2022-06-02 13:31:05.005267+00
22	flags	0004_remove_flag_hidden	2022-06-02 13:31:05.006602+00
23	flags	0005_flag_enabled_by_default	2022-06-02 13:31:05.00767+00
24	flags	0006_auto_20151217_2003	2022-06-02 13:31:05.008741+00
25	flags	0007_unique_flag_site	2022-06-02 13:31:05.009753+00
26	flags	0008_add_state_conditions	2022-06-02 13:31:05.010755+00
27	flags	0009_migrate_to_conditional_state	2022-06-02 13:31:05.011769+00
28	flags	0010_delete_flag_site_fk	2022-06-02 13:31:05.012796+00
29	flags	0011_migrate_path_data_startswith_to_matches	2022-06-02 13:31:05.013798+00
30	flags	0013_add_required_field	2022-06-02 13:31:05.0191+00
31	sessions	0001_initial	2022-06-02 13:31:05.037524+00
32	song_signup	0002_auto_20220531_1820	2022-06-02 13:31:05.082734+00
33	song_signup	0003_auto_20220531_2033	2022-06-02 13:31:05.141221+00
34	song_signup	0004_songrequest_priority	2022-06-02 13:31:05.152589+00
35	song_signup	0005_songrequest_position	2022-06-02 13:31:05.16585+00
36	song_signup	0006_auto_20220601_1055	2022-06-02 13:31:05.19118+00
37	song_signup	0007_songrequest_cycle	2022-06-02 13:31:05.202453+00
38	song_signup	0008_songrequest_is_bonus	2022-06-02 13:31:05.214274+00
39	song_signup	0009_auto_20220602_1138	2022-06-02 13:31:05.25036+00
40	flags	0012_replace_migrations_for_wagtail_independence	2022-06-02 13:31:05.254698+00
41	song_signup	0010_singer_lscy_position	2022-07-05 12:50:20.647579+00
42	song_signup	0011_auto_20220703_2039	2022-07-05 12:50:20.705024+00
43	song_signup	0012_auto_20220704_1655	2022-07-05 12:50:20.733846+00
44	song_signup	0013_auto_20220704_2037	2022-07-05 12:50:20.755595+00
45	song_signup	0014_songrequest_placeholder	2022-07-05 12:50:20.767452+00
46	song_signup	0015_singer_placeholder	2022-07-05 12:50:20.780328+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: twistdbadmin
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
pv4z8a0pe89kx1a1xxeuyxpviq3zga1x	.eJxVjMEOwiAQRP-FsyGE4i549O43kGUBqRpISnsy_rs06UEvk8m8mXkLT9ta_NbT4ucoLsIocfoNA_Ez1Z3EB9V7k9zqusxB7hV50C5vLabX9ej-HRTqZazRsbMUCI1WoJQZ7pwtRUBkCxEZE2jMKmlmdlnbKbs0MXIYChrE5wsLdTiA:1o2xst:ZbTjpD0vLyXMPe_3KGY0BxNdxEPAlYQrG86jQc4s47I	2022-07-03 16:34:47.356787+00
slr3qngfv607kd9fnslov3tou8x7f5mq	.eJxVjEEOwiAURO_C2hAofCAu3XsGAvyPVA0kpV013l2adKG7yZs3szMftrX4rdPiZ2RXphW7_MIY0ovq0eAz1EfjqdV1mSM_FH62nd8b0vt2un8HJfQy1uTAUAIrJKAcUajJRtQgoiET0TmpMFm0mCG4mKdsSWQLAxudcpDs8wUFqzhC:1o2xyv:WALmQnnAagtKocy_XbXDQ18luA0klRhVOyK9PaMkbOM	2022-07-03 16:41:01.282939+00
wosxzkv9b1o2qxc5uj4ob9i4w4s2u902	.eJxVjEEOgjAQRe_StWnoTG2nLt1zhmaYDoIaSCisjHdXEha6_e-9_zKZt3XIW9Ulj8VcjDOn361jeei0g3Ln6TZbmad1GTu7K_ag1bZz0ef1cP8OBq7Dt8bgPEpSaHzEIIXP4AN7Am0cRexRKYmDIORS8pGgJxWKPcTgEKEx7w-ssjY2:1nwn3P:lJz3pJy6yDLw-mqseSXSlVxmW6i6N7c1kFxghXN-EuE	2022-06-16 15:48:07.330102+00
7fo3lfpn8mhgdcca8ur2vxibssbefq6t	.eJxVjEEOwiAQRe_C2hCgnQFcuvcMZGBAqoYmpV0Z765NutDtf-_9lwi0rTVsPS9hYnEWXpx-t0jpkdsO-E7tNss0t3WZotwVedAurzPn5-Vw_w4q9fqtqTDYrNhB0aSM9gqNU9Zz8TbmguTHwaMm4NGBQTIApuCgXdIJIVrx_gDa-Dcp:1nwniF:rjyW8Igo_jSi_RQ23khcDJ3g3F0nRLJgbNi5ejC35pY	2022-06-16 16:30:19.169507+00
ts268mp3zat3x7xic637h95bp88teh5z	.eJxVjMsOwiAQRf-FtSED9MG4dO83kBkGpGpoUtqV8d-1SRe6veec-1KBtrWEraUlTKLOyoA6_Y5M8ZHqTuRO9TbrONd1mVjvij5o09dZ0vNyuH8HhVr51qPY5JBiGixkY9m4zDg47MB0DnMPRpJ3QgSxFwDx0SAIeRyJPces3h8AnThR:1nwnlo:m8myYxDu1IHaPJgX3_yvF7UNxtN5p74Ndk99bfKqSRY	2022-06-16 16:34:00.419651+00
a5qnduxep3vaey0kuq1e9s1sbpjs5xc2	.eJxVjEEOwiAQRe_C2hApQ5m6dN8zNDMwSNVAUtqV8e7apAvd_vfef6mJtjVPW5NlmqO6KGPU6XdkCg8pO4l3KreqQy3rMrPeFX3Qpsca5Xk93L-DTC1_6z51eGaPXYjiIYgzLoFBRhJn7YCQLFoXImMKbIAkkQXfIwIkDwOr9wcJbjgj:1nwnpl:3WOZfZsLKNYZV7MXazFnXndNK8qzqmKNyUwhuCFalR0	2022-06-16 16:38:05.78146+00
163mgsyn88wjkooq55isr18raypqktvj	.eJxVjEEOgjAQRe_StWnoTG2nLt1zhmaYDoIaSCisjHdXEha6_e-9_zKZt3XIW9Ulj8VcjDOn361jeei0g3Ln6TZbmad1GTu7K_ag1bZz0ef1cP8OBq7Dt8bgPEpSaHzEIIXP4AN7Am0cRexRKYmDIORS8pGgJxWKPcTgEKEx7w-ssjY2:1nwnqB:GMdsainHaoUEzlABCMX_-HTdIfxRcCy2g8o5yBThtQ8	2022-06-16 16:38:31.730287+00
acc6u9ej9buxssdbldhldm2jwf8ls920	.eJxVjEEOgjAQRe_StWnoTG2nLt1zhmaYDoIaSCisjHdXEha6_e-9_zKZt3XIW9Ulj8VcjDOn361jeei0g3Ln6TZbmad1GTu7K_ag1bZz0ef1cP8OBq7Dt8bgPEpSaHzEIIXP4AN7Am0cRexRKYmDIORS8pGgJxWKPcTgEKEx7w-ssjY2:1nwnqb:fysVLU0O-xfIr1MXxWq-XhMwimtLzcptqP4IXo2eQvc	2022-06-16 16:38:57.55207+00
a03cc1lph4yh9p5fe2j7itg3gt3fk7jw	.eJxVjMsOwiAUBf-FtSE8bAGX7vsN5D5AqgaS0q6M_65NutDtmZnzEhG2tcStpyXOLC5CG3H6HRHokepO-A711iS1ui4zyl2RB-1yapye18P9OyjQy7c2GJTO3iAFf_aMeUAD5AmctY5RO58UjqwyIgHQkIz17IBMsKOjROL9AScaOU0:1nwnuC:ZuYDwoCrl6SeqxQH1fxL2DFqFHfKNE-p0Gp3rVOTbqI	2022-06-16 16:42:40.231764+00
zbk7110f51ifg4mbqtb0ht1fy5fjdlax	.eJxVjMsOwiAQRf-FtSEMFAZcuvcbyNAZpGrapI-V8d-1SRe6veec-1KZtrXlbZE5D6zOCjp1-h0L9Q8Zd8J3Gm-T7qdxnYeid0UfdNHXieV5Ody_g0ZL-9YWEUIF42ohEOML9CEKGkRbpEvVo7dgJbngIkdDyOyRXOIarAdM6v0B6Vg3JQ:1nwo10:pO4anpONgiySx20uZ7E2BMSpiLJkpu298hVPqVjObPI	2022-06-16 16:49:42.742369+00
vx5j70bafj4q6govpqbn01n9zxuqf7qm	.eJxVjEsOAiEQRO_C2hCbj4JL956BNN0gowaSYWZlvLtMMgvdVeq9qrcIuC4lrD3NYWJxEWDF4beMSM9UN8IPrPcmqdVlnqLcFLnTLm-N0-u6u38HBXsZ64icVbKsz8eTHxFMtNob1MkpBnDkyREpAMoUrSPHoGzW2SkzvIzi8wUb6Dhp:1nwo2a:wJ8i5hO2fszmcOffDqHND3Ak9k1q3Er2WIynHY4i2Bc	2022-06-16 16:51:20.902284+00
y6ywtyejn2l6yyawuaeiwn9ly1zv04j4	.eJxVjMsOwiAQRf-FtSG8BgaX7v0GwhSQqoGktCvjv2uTLnR7zzn3xULc1hq2kZcwJ3Zm0rLT70hxeuS2k3SP7db51Nu6zMR3hR908GtP-Xk53L-DGkf91qQ1CmMzQimayAGokm00DoUrIhOhTBGBrJRKCQQg5z1i8dIbl7xg7w_6cjc3:1nwo2t:rwCiR0tHu9YE9yuvLB9CfHjoKfJ-jHIotVr72qdENdQ	2022-06-16 16:51:39.199205+00
7ugbkp7d6ugdh4x1n1temcnwzbi6bozt	.eJxVjL0OwiAYAN-F2ZAg0IKju89Avr9K1UBS2qnx3ZWkg653l9tVgm3NaWuypJnVRZlRnX4hAj2ldMMPKPeqqZZ1mVH3RB-26VtleV2P9m-QoeX-ZRZBCsguhtE7ihhkcgZCEEAiEHcmiz7aCS2z_fZ2iCaaINb4wan3B0lnOQU:1nwo3D:oZpy_jU2rTc13l2X3Nbshu3MAcE6_X1r7Gu590ffLF8	2022-06-16 16:51:59.257344+00
mudh0codmwr29jnu69l207meur4i22oe	.eJxVjDEOwjAMRe-SGUVpS2LDyM4ZIttxSAGlUtNOiLtDpQ6w_vfef5lI61Li2nSOYzJn06E5_I5M8tC6kXSnepusTHWZR7abYnfa7HVK-rzs7t9BoVa-tSZ0R0AfesJeTuBIc4eSQxYfAotHLw4IBwJkZFAamMAhBGUv3pn3Bw5pOE4:1nwo3b:Rr7jNqDhGplg413sTdZF-c5pJF-T_3v0rnUmrqMcgBA	2022-06-16 16:52:23.587462+00
mwb9m8duw6hcxv44s7b5ins818gcuuge	.eJxVjDsOwjAQBe_iGln-xR9Kes5g7dprHEC2FCcV4u4QKQW0b2bei0XY1hq3QUucMzszO7HT74iQHtR2ku_Qbp2n3tZlRr4r_KCDX3um5-Vw_w4qjPqtvRZaEcgcbMJEvqAxVofgsrEoJitBS2Fk8YU0ZIAgpdeEBZVyLonA3h8HQjgE:1o4N2x:U16JxwHubrsD_EMAAvzDJ_dzcNUTXe3reubFstrwCPk	2022-07-07 13:38:59.404989+00
lchqy1jwsysx7qe460abrj1g8fm5534u	.eJxVjMEOwiAQRP-FsyGASwGP3v0GsiyLVA1NSnsy_rtt0oPOcd6beYuI61Lj2nmOYxYXoYM4_ZYJ6cltJ_mB7T5Jmtoyj0nuijxol7cp8-t6uH8HFXvd1lZncMmVYEFZVkltQSBtTCHjE2YerNNA3mUu1qDhAZQPdC4AVDyLzxf5wjgA:1nwo3x:Uy0IRBieSLNe77ExlFuyV1WkEuUs2ooOmg2B3KPrlEs	2022-06-16 16:52:45.459567+00
bby5dvm7e3hromggx7jmodltbe1x2ad8	.eJxVjDkOwjAQRe_iGlnjJV4o6TmDNeMFB5AtxUmFuDtESgHtf-_9Fwu4rTVsIy9hTuzMJLDT70gYH7ntJN2x3TqPva3LTHxX-EEHv_aUn5fD_TuoOOq39hJQ6EIgrUjKqUiIBixQMn6y4JW0loRxRkyqyCiNElph0eQsxiiAvT_dgDb2:1nwo4w:lcoJEyxFVL62kn8Qs1qvfOCH30kKh0rw_TRgoIkPYUw	2022-06-16 16:53:46.703489+00
xx1tyyert399h9do3daam75f1arhyg7y	.eJxVjEEOwiAQAP_C2RCgUMCj976BLLsgVQNJaU_GvxuSHvQ6M5k3C3DsJRw9bWEldmVKsssvjIDPVIehB9R749jqvq2Rj4SftvOlUXrdzvZvUKCX8bV5MgSeEAidQp1jIj8Zm2U0ZJwGtCoaT94L43x0kjQqOQtBNKfk2OcLK9A4qA:1nwo52:XZhDZyie4epS_nS2y_QGHxxQSUnTK9W4bfr518mUSEI	2022-06-16 16:53:52.218917+00
iphln9x9vzc8yobwp9163hskxhqpdwbz	.eJxVjMsOwiAQRf-FtSEwFCgu3fsNZIaZStXQpI-V8d-1SRe6veec-1IZt7XmbZE5j6zOCkCdfkfC8pC2E75ju026TG2dR9K7og-66OvE8rwc7t9BxaV-62SxGNcNznfibeghCccCJJBCLy5i5GjJpz6YQMQuGIYYrbgB2Q8G1PsD84A3rQ:1nwoAW:3K5LOKqwL4ShHx5QsGLg3X3aAZkSntN4FhWj76BN-wY	2022-06-16 16:59:32.687207+00
ou900lqdfkbsax0teb9svywqfojmuft0	.eJxVjDsOwjAQBe_iGllhN15sSnrOEO3HxgGUSPlUiLtDpBTQvpl5L9fxutRunfPU9ebODtAdfkdhfeRhI3bn4TZ6HYdl6sVvit_p7K-j5edld_8OKs_1W2NqNAdWsMRJAsQsERCNsFhhVBJiPGXQ0mA0IxAqRAFakWOrIbr3ByLPOJU:1nwoBB:om-ashs9gISj1mehwE8sBZlTGdNQRSPCgDTHA2dG2mw	2022-06-16 17:00:13.112538+00
7uict1xr4ny50x2gq455vc0x5bpiv768	.eJxVjMsOwiAQRf-FtSFlyqPj0r3fQGAYpGogKe3K-O_apAvd3nPOfQkftrX4rfPi5yTOArQ4_Y4x0IPrTtI91FuT1Oq6zFHuijxol9eW-Hk53L-DEnr51oSJIKJFm62LiIMz7LIa00iGlTbaqmECzKQBOKICxc5qcqR5SsQo3h_7fDfK:1nwoKg:o9JEEqzIHqcr7Crz7noqTfYmsgMiuPQtrFG36RY3xQQ	2022-06-16 17:10:02.414053+00
vg0dxkh129xsfy3wbaqdyotwysvr0skr	.eJxVjDsOwjAQBe_iGlmLN_6Ekj5nsHb9wQFkS3FSIe4OkVJA-2bmvYSnbS1-62nxcxQXoYw4_Y5M4ZHqTuKd6q3J0Oq6zCx3RR60y6nF9Lwe7t9BoV6-tdY5R3SOjEVIAxgKFsBEM6izQiQ3ckalObuBFY7EASwwRh00JI0g3h_xbjdj:1nwoMV:MX68Aluosn-8IaGSLeqCqgzYp3GCKd6m20cZW1j1sig	2022-06-16 17:11:55.070619+00
qj25orpqk1dbmkn8t7g4vj59e1tgrp3j	.eJxVjEEOwiAQRe_C2hBgCrQu3XsGMsxMpWpoUtqV8e7apAvd_vfef6mE21rS1mRJE6uzclGdfseM9JC6E75jvc2a5rouU9a7og_a9HVmeV4O9--gYCvf2hOGbFwPvYsQsxH2AdmNQOAwZkArQTCK70bwlvzAMBAzgOPOBkPq_QELszgm:1nwosV:59GNMWZbzDeIjumWKba1rg7Vc6dYLJMitjh4_VpAUJc	2022-06-16 17:44:59.137665+00
odfunaq5pxv93xv60tmup01iwae7fjie	.eJxVjDsOwjAQBe_iGlmR1_GHkp4zWOv1Lg4gR4qTCnF3iJQC2jcz76USbmtNW-clTUWdlQnq9DtmpAe3nZQ7ttusaW7rMmW9K_qgXV_nws_L4f4dVOz1WxOJRyAWC0VQrBPiCIADxGBlJA4QjTNGvAWhAYLYEj0ShtFmF7J6fwA87Djk:1nwotk:J5E6gW3Ikjrq0bmoEiI7L3jO7hfuCmZ67rE2iBge0LY	2022-06-16 17:46:16.31994+00
96j53vggrwvyv36ne4298flt0zdujdfg	.eJxVjMsOwiAURP-FtSFclJdL9_0GcoGLVA0kpV0Z_12adKGZ3Zkz82Yet7X4rdPi58SuTDp2-oUB45Pq3qQH1nvjsdV1mQPfFX60nU8t0et2uH8HBXsZa6WkA6dQU9YGXFRgs9E22ouIgFqSOOfBIacwkkkIUlKBiA6MgxDY5wvwAjex:1nwouH:JJsSt_QaYlx1Nr6ibOTnFlAic5iHdxkB39XuBnuRCME	2022-06-16 17:46:49.676972+00
5elu0kqhqskdomnafcr3jnzsyt4zjdcp	.eJxVjDsOwjAQRO_iGlkGxz9K-pzB2l1vcADZUpxUiLvjSClgynlv5i0ibGuOW-MlzklchVbi9Fsi0JPLTtIDyr1KqmVdZpS7Ig_a5FgTv26H-3eQoeW-dhaZPQetJtMzkAoWYTDWa04TeaRAaM5BdeZSl0Ebk8hqDxcy7MTnCw0xOE0:1nwoyq:9yR4tZEc0V5jxBMalBgUcbNYCOGIXPtP9_0305kTiqo	2022-06-16 17:51:32.336557+00
n1fottcwjtg3yts6ai9cxlq181ziaxlx	.eJxVjEEOwiAQRe_C2hBhKFCX7j0DYZhBqgaS0q6Md7dNutDtf-_9twhxXUpYO89hInERoMTpd8SYnlx3Qo9Y702mVpd5Qrkr8qBd3hrx63q4fwcl9rLVPCJ4iziCJsOoUwYgImvO2VBk53yGjSUG1HmAzMqpIVqnWPmBlBOfLyZSOG4:1nwpYi:U4vauVZF5z2amfXcJsoy6rDmTLC0hQ2__bQAia6zegM	2022-06-16 18:28:36.351555+00
sjevssbipn6g56nz7u634jxm39g0qu05	.eJxVjDsOwjAQBe_iGlnx2vGHkj5nsDbeXRxAiZRPhbg7spQC2jcz760yHnvNx8ZrnkhdlTPq8juOWJ48N0IPnO-LLsu8r9Oom6JPuulhIX7dTvfvoOJWW10MB-SOYmd705MEKzYkMEl6TuKsZYkFAAFHm4AoGeclOCnOexNBfb4QKjfm:1o2xtR:L80GbWy1N8gXgld1w8tUJfTuO4JzAye2ocB74Q3f2q4	2022-07-03 16:35:21.298939+00
ujjqp3qzwfbe3damextvp1p8nokzo4u3	.eJxVjDsOwjAQBe_iGlkbr-2NKek5g7X-4QBypDipEHeHSCmgfTPzXsLztla_9bz4KYmzQCVOv2Pg-MhtJ-nO7TbLOLd1mYLcFXnQLq9zys_L4f4dVO71W0cCG61zaC1ojTTAqIhAZw0FEfOQUgHEYKmACRoUGWZWhkwxZXRZvD_EJTa3:1nwpdh:zmu6eQaRSycTXW_3_AndsACkJthWXOyP9uJEtlJqyqI	2022-06-16 18:33:45.015742+00
ayekghds2ord536km0rnoi1pirmj87ql	.eJxVjLsOgkAUBf9la7O57IvV0p5v2NyXghpIWKiM_y4kFNqemTlvU3Bd-rJWncsg5mIab06_IyE_ddyJPHC8T5ancZkHsrtiD1ptN4m-rof7d9Bj7bc6uQzEKuKcjyE6JEihzdEjsBcPyozBpwbkdmYK5CiD5pC2qFFpW_P5Av7QOBM:1nwq6Q:M4uiXVyipl8DWERYRmyMxbb3TYSF52TaWYs3RxgATaQ	2022-06-16 19:03:26.733437+00
faz3sgy95ofctik4366i9lzyhkwzpx3a	.eJxVjEEOwiAQRe_C2pCBDi24dO8ZyFBmpGpoUtqV8e7apAvd_vfef6lI21ri1niJU1ZnhVadfsdE44PrTvKd6m3W41zXZUp6V_RBm77OmZ-Xw_07KNTKtwZyQ7AiYJA8Q-586j1AGnIWg0ksJQqebY8dOxRy7MSLAZEAiCGo9wcPQDg_:1o2xuN:S9yXGcXz5t209Q_AodQCeeWWdy-Ftnfqqmyf87K7O2U	2022-07-03 16:36:19.962371+00
vsk4b9om4eb9svhq1qi0jng2s64e2w64	.eJxVjEEOgjAQRe_StWnoTG2nLt1zhmaYDoIaSCisjHdXEha6_e-9_zKZt3XIW9Ulj8VcjDOn361jeei0g3Ln6TZbmad1GTu7K_ag1bZz0ef1cP8OBq7Dt8bgPEpSaHzEIIXP4AN7Am0cRexRKYmDIORS8pGgJxWKPcTgEKEx7w-ssjY2:1o0WuG:-XsdyRRobzcZHMl6_5Xr6bUECCeRJN327ojM2kbji-Y	2022-06-26 23:22:08.107138+00
76e6ib54kgp4zd4sx4sm87at2eih27sl	.eJxVjEsOwjAMBe-SNYqS2GkxS_Y9Q-TEDi2gVupnhbg7VOoCtm9m3ssk3tY-bYvOaRBzMYjm9DtmLg8ddyJ3Hm-TLdO4zkO2u2IPuthuEn1eD_fvoOel_9YUqhMMdPYxVGKERpxACyqtbyEEQYiRsiq6wD6C1hypQENFEaM25v0B5Po3Uw:1o2xzo:LVpBfFg8dTAprY-v_PGtHAnd0wY3EyVDzXTihqRvvIE	2022-07-03 16:41:56.299397+00
fg4auwm8dwafs8jcwr7it5b9ns7vlmt6	.eJxVjDsOwjAQBe_iGll24nxMSZ8zWOvdFxxAthQnFeLuKFIKaN_MvLcKtG8p7BVrWERdVevU5XeMxE_kg8iD8r1oLnlbl6gPRZ-06qkIXrfT_TtIVNNRg6ywBzVkMHcRELAbO5qtmTvvjMDHiMG6lnhAHJk8S2_t0Hs0zqnPF2FOObU:1o2WLz:WhLlHBz9fX6SlSCoRlU1tFgEsBxOm236SqjU_PbAc4M	2022-07-02 11:10:59.186359+00
3szeb87y06fmp4j19q6zw1dxcbmgf85n	.eJxVjEEOwiAQRe_C2hBaBjq4dO8ZyDAMUjVtUtqV8e7apAvd_vfef6lI21rj1mSJY1ZnBU6dfsdE_JBpJ_lO023WPE_rMia9K_qgTV_nLM_L4f4dVGr1W7vAjMYOhsEioC9gC3qbOwJkSR2Ikx6JrfeUku8FmU1xAyQMFKCo9wf7hTgd:1o2y5U:SORsmGfHdG1_28Lc5TAs9wRlxni6porOVt7BMW72fkA	2022-07-03 16:47:48.964476+00
7q91s4idlup24e0h83akxlpwik04judl	.eJxVjMEOwiAQBf-FsyFAgQWP3vsNZIFFqoYmpT0Z_92Q9KDXNzPvzQIeew1Hpy0smV2ZtuzyO0ZMT2qD5Ae2-8rT2vZtiXwo_KSdz2um1-10_w4q9jpqKRAU2GjQTJmgiElEVEU6RHLgi7HJAzjpUbsE5LzO0UtlQBqLQrPPFwdoN4s:1o2yBu:QZajFg6DTKDP9glf1KU2_VSXzjMjgv66Tgk_8Z6WBDk	2022-07-03 16:54:26.464576+00
a93yx7i120nupaph38rw2n0639pacji9	.eJxVjMEOwiAQRP-FsyFAaRc8evcbyHZZpGogKe3J-O9K0oNe5jDvzbxEwH3LYW-8hiWKs7AgTr_ljPTg0km8Y7lVSbVs6zLLrsiDNnmtkZ-Xw_07yNhyX5NiAE4-WYoTmZScJc1-8I5GQ0pB8mZ2ygBqMBAV8jfdpIl1GmAU7w8orzhN:1o2yCD:LNGxeWMF4K0eB5Xx__w8A1FRlmVljoyxBQHN5OX_Qjo	2022-07-03 16:54:45.288556+00
ergjtksode4hk5rqpfmjeybcnmwwa35b	.eJxVjEEOgjAQRe_StWlKpTDj0j1naGamg0UNJBRWxrtrExa6-_nv5b1MpH3LcS-6ximZi2nBnH5PJnnoXEm603xbrCzztk5sq2IPWuywJH1eD_cvkKnk2g0KSBywdw7wHJB78p2w910C-M4eVLDzDbILKl6U0XObGhIYx7E17w_zSzgk:1o2yIO:pVsT4-2AgBhAl2FO_Drz_8HOJ8JP7mEFOUMM1MuYOb0	2022-07-03 17:01:08.331177+00
ff39gtl8g1sd8wsuczdj5ghgbgbo9ssi	.eJxVjDsOwjAQBe_iGlnr-BdT0nMGa71e4wBypDipEHeHSCmgfTPzXiLitta4dV7ilMVZmCBOv2NCenDbSb5ju82S5rYuU5K7Ig_a5XXO_Lwc7t9BxV6_9cCIzgdtVTYKiCygoxIIwNqMoEPwAzOMXLROrIyzJSMXr1IavTEk3h8Nejhk:1o2yKM:skMJ03DUFqTPI5BS1JiR55IC0D9c-ZPHvO1QQFJBsYw	2022-07-03 17:03:10.373049+00
j32gdf3y5wj6191qyq2rpelf8zmgyxkz	.eJxVjEsOAiEQBe_C2hCGn7ZL956BNE0jowaSYWZlvLuSzEK3r6reSwTc1hK2zkuYkzgLp8Thd4xID66DpDvWW5PU6rrMUQ5F7rTLa0v8vOzu30HBXkZNZLIzlihj0nxyxA4hAqNXgHycImTtk4KvaNEmsKi8J6s1gIHJiPcHRsI4zg:1o2yMd:y0k-cXItk7EVrRKGVR523NXngNGFXRLJz17LcCmBQuY	2022-07-03 17:05:31.458024+00
jlxd3gs4kfjxcuz57a6pbk8cxdmksxma	.eJxVjEEOwiAQRe_C2pABmaG4dN8zEGCoVA0kpV0Z765NutDtf-_9l_BhW4vfel78zOIiUInT7xhDeuS6E76Hemsytbouc5S7Ig_a5dg4P6-H-3dQQi_fOmYDYEFjZhg4arSBMAYdCQgnOBtUlJIl6wxal_XEylkiBB4SOGTx_gDsxTcd:1o2yVZ:IAmdyIMWhAH0Dz-8oshmAddPWX1FbNdIC4YI5pC2nu0	2022-07-03 17:14:45.296857+00
dxcpv8vo8izkgstkjwzgf9ue373q1tmb	.eJxVjEEOgjAQRe_StWnoTG2nLt1zhmaYDoIaSCisjHdXEha6_e-9_zKZt3XIW9Ulj8VcjDOn361jeei0g3Ln6TZbmad1GTu7K_ag1bZz0ef1cP8OBq7Dt8bgPEpSaHzEIIXP4AN7Am0cRexRKYmDIORS8pGgJxWKPcTgEKEx7w-ssjY2:1o2xox:S18fJzHkwVFo3B5U6VMVYGfSxsJF3G6m6kgLmOPLRtI	2022-07-03 16:30:43.430842+00
7ccjwr2dat05cl5fdb2xxqfw4c1x81sr	.eJxVjEEOwiAQRe_C2pBCHYZx6b5naGAGpGpoUtqV8e7apAvd_vfef6kxbGsZt5aWcRJ1UWDV6XeMgR-p7kTuod5mzXNdlynqXdEHbXqYJT2vh_t3UEIr35ptR5RT77KngN73JLEzFjkxCIgzDBgz9SyW0BokQHG54wQIEs6o3h8H3jgB:1o2yWQ:Kq493y_2UA4d6mNGmN6hxurpRu4etNbsK8x85kZZRyw	2022-07-03 17:15:38.368209+00
amkijlor8kwqp0gr8o5eqv3hb5bvqiss	.eJxVjMsOwiAQRf-FtSF1YHi4dN9vIDBMpWogKe3K-O_apAvd3nPOfYkQt7WErfMS5iwuQjlx-h1TpAfXneR7rLcmqdV1mZPcFXnQLseW-Xk93L-DEnv51gbUGa0ihzopVOSNTc5pYETyUZHmKaMfBp81IDrwnCyZCQxZGzOCeH8A3Q83OQ:1o2xpa:tLRqAgz2k4B7Qvqz-BRFiFFcX5Pv766dsMDWiFNJwfk	2022-07-03 16:31:22.95771+00
e08c5lr0qv5yxldekm7lkckcplnmns2v	.eJxVjMsOwiAQRf-FtSHDo1RcuvcbyMAMUjWQlHZl_HfbpAvd3nPOfYuA61LC2nkOE4mLMF6cfseI6cl1J_TAem8ytbrMU5S7Ig_a5a0Rv66H-3dQsJetdpqiN84AnJ0GpywlC0DJZ0-YhoQ8ACsaSSvOG4qjd6hiRksqA2vx-QICyDh-:1o2xqZ:p5ss882YYxD8bnDHNWhUddB6Hl_XuXeeKMBQB6zhuGQ	2022-07-03 16:32:23.526632+00
bzy58jq5wfcsqbpgkroma5b2gimz6fq1	.eJxVjMsOwiAQRf-FtSFUuEBduvcbmhkGbNVA0sfK-O-mSRe6veec-1YDbes4bEueh0nURcGq0-_IlJ657kQeVO9Np1bXeWK9K_qgi741ya_r4f4djLSMey2G0ZVgQQTPCT1cdAjFeOYoCQGcTJTOS5KecjYRsBmRvStngvp8AReCOHI:1o2yep:EH3aJ9gpq6uKroO15GPz3QbdfMDB3DWg-NGN7VQM9Pg	2022-07-03 17:24:19.733377+00
5epou5thqwdr7o3sbtn3rbwhm41dudgx	.eJxVjMEOwiAQRP-FsyECC6JH734D2WUXqRqalPZk_HfbpAc9zGXem3mrhMtc09JlSgOri_KgDr8lYX5K2wg_sN1Hncc2TwPpTdE77fo2sryuu_t3ULHXdR05B_IGQEyMEgWKA3Rk6Qws1pZwMniMa5wtIt5xLiXHYAkJuWBWny8XbzlN:1o2yn3:RBv0yFOC2e52VhPgQPYmJ1vyRd5IFibhVUic3bK7N3s	2022-07-03 17:32:49.888187+00
eytbq5ou0ist9fkghfb1n2w74rb6slbq	.eJxVjEEOwiAQRe_C2pAKDBSX7j0DGWBGqoYmpV0Z7y5NutDte-__twi4rSVsjZYwZXERAOL0CyOmJ9Xd5AfW-yzTXNdlinJP5GGbvM2ZXtej_Tso2Epf-0TGk8kcLahoLUZwnREMRqvBaxo18ui4Cw1sjWZFSrFzGs_OshWfLxsFOCY:1o2yn3:CGtwexJ7jquk5GglscNvqRkPg6qlYPW6h1FN13r2uGs	2022-07-03 17:32:49.994867+00
ywas9oetl00vbdmykra6nhn0569czvvd	.eJxVjMsOwiAQRf-FtSEtw0Ncuu83kGEGpGogKe3K-O_apAvd3nPOfYmA21rC1tMSZhYXYaw4_Y4R6ZHqTviO9dYktbouc5S7Ig_a5dQ4Pa-H-3dQsJdv7SmCd4ZtHj0bjCoBA7kMgxoVRKBsE2TWRGevXbKQSZO2Eb1xg2En3h8dyTh7:1o2z4d:jRmdeJ-gh9W7rAqUuGmSpSWBByh6X-MJauiWTryMT_I	2022-07-03 17:50:59.426561+00
w3zqv3qi9v8ssu7vz5ddy40ivayydfg7	.eJxVjDsOwjAQBe_iGlmO_6ak5wzWrneDA8iR4qRC3B0ipYD2zcx7iQzbWvPWeckTibNwUZx-R4Ty4LYTukO7zbLMbV0mlLsiD9rldSZ-Xg7376BCr986eEZniVgDa0TFJjjvImsGLobGFGgwxUevBm2SwmTjGCgpmxA1JxDvDygKOHs:1o2zIw:9ENwSyPVCnC_PERe0t46QhuF-GJZtTLUJlCYdYApznY	2022-07-03 18:05:46.409281+00
a7az8g1h0cvdqgmd4cizzv713je4v63q	.eJxVjEEOgjAQRe_StWkK7ZTWpXvOQKYzg0UNTSisjHcXEha6fe_9_1YDbmsetirLMLG6Kojq8gsT0lPmw_AD53vRVOZ1mZI-En3aqvvC8rqd7d9Bxpr3dQIP3DaBIUDorEmOBKwHIeMSU0SPO40SQBxg03StIbSCPBqD1I3q8wX9yjgx:1o2zMd:a5O2e9cvYl7XH-CM4bjvi15jfyZNM-KTJdYrlrDalHk	2022-07-03 18:09:35.679026+00
ycdmz5c6zl4i55d99fpbwnaajlmw9qxt	.eJxVjEEOwiAQRe_C2pBSYGBcuvcMzQwDUjVtUtqV8e7apAvd_vfef6mBtrUOW8vLMIo6K-jU6XdkSo887UTuNN1mneZpXUbWu6IP2vR1lvy8HO7fQaVWv3X0AiaDxCRMYEoIzhcnbHuE2CFbQteHghEYCzlnkiTJ3HsbCbGz6v0BECY4JQ:1o2zNg:iBSFVWwVd1Yq6pw9qIYXhy5PZFKwg6WqnlSdbAWiJRA	2022-07-03 18:10:40.148874+00
9auctrsprqrsocccktdlvktmwdj6aknm	.eJxVjMsOwiAQRf-FtSFQ3i7d-w1kYAapGkhKuzL-uzbpQrf3nHNfLMK21rgNWuKM7MysZKffMUF-UNsJ3qHdOs-9rcuc-K7wgw5-7UjPy-H-HVQY9VuLnAkItMXgghUklU7aeVQmu0JKBxmM8UbqYpyz6NEWSQpIBDdNWDx7fwAI4jfL:1o2zOA:rYG-AcnyZCBekXPATvUCNAB6ZpjY71ScC16xvWWxmVs	2022-07-03 18:11:10.808858+00
epe5fpjgndxxrohwsnos6618uxa8ilco	.eJxVjDsOwjAQBe_iGllm_dFCSc8ZrLf-4ABKpDipEHeHSCmgfTPzXipiXVpce5njkNVZBVKH31GQHmXcSL5jvE06TeMyD6I3Re-06-uUy_Oyu38HDb19a3IWjlG55qMlz6EESwQrGYUThILxPoXCQBUmAVsxcCcGB-OsUe8PENE4JA:1o2zuc:43gPvmM_7SEC_N-mi_sdNtfZFNI2cS9jnvNMXbtayRY	2022-07-03 18:44:42.124787+00
042vuoml6810c4wgu4i8jme63sd2ddo8	.eJxVjDsOwjAQBe_iGllx4i8lPWew1rtrHEC2FCcV4u4QKQW0b2beS0TY1hK3zkucSZyFceL0OybAB9ed0B3qrUlsdV3mJHdFHrTLayN-Xg7376BAL986awTrPA9kPNgQnB3ZMdMAIwMB2qwQ0-QSmETK5UkHNopIm0DEPon3BzpDOZs:1o2zwG:LDSEQKCSUWnUf8FRs1r-Wzm6UDKGSOKUYxMb4DRJXVY	2022-07-03 18:46:24.129737+00
d1r8fn2bmg8lg2iki82gi30200lfwlci	.eJxVjMsOwiAQRf-FtSGUxwAu3fsNZIBBqgaS0q6M_65NutDtPefcFwu4rTVsg5YwZ3ZmoNjpd4yYHtR2ku_Ybp2n3tZljnxX-EEHv_ZMz8vh_h1UHPVbK1uUBAUTeS3AxkykFTnQThgtTVEQJ1e8QG8wlZKyjsKCMdmiAOkte38A6cY3Xw:1o30Bd:vdhTxh-otrkQCLl9irzerspg3pItQexuquBFSqQr7Xg	2022-07-03 19:02:17.527236+00
p0ey37611vdz8zk2ykp80jrdxwvte0os	.eJxVjEEOwiAQRe_C2hCByRRcuvcMZGAGqRqalHbVeHdt0oVu_3vvbyrSutS4dpnjyOqiENXpd0yUn9J2wg9q90nnqS3zmPSu6IN2fZtYXtfD_Tuo1Ou3tmKBChqyntAjGEPFAKHLAXigwiYL0FAciDjnzTmjLS5xSBBCcEW9Pw4TOD0:1o4N3V:7wH4KMcMcWvW1c7yoLARg6PoSZeDhy2bIf60shemysc	2022-07-07 13:39:33.500095+00
i4f0303jvvz2pgvxengglh3zpg1p5e98	.eJxVjMsOgjAUBf-la9NcakupS_d-A7mvWtRAQmFl_HchYaHbmTnnbXpcl9KvVed-EHMxbTSnX0jITx13Iw8c75PlaVzmgeye2MNWe5tEX9ej_TsoWMu27lBa1ZDBOQmSUsqQOpbcesUNNA2TkPoUOJyBKTIAOgBRCp5cE83nCzYTOO8:1o4N8z:RQNCfsqw7TVRs4iOXx0I7ZCBsxWr8vauyKCV75fcRgc	2022-07-07 13:45:13.610855+00
vnp94ln5p0ob77gsd5tuqlw4miqyatxu	.eJxVjEEOgjAQRe_StWnoTG2nLt1zhmaYDoIaSCisjHdXEha6_e-9_zKZt3XIW9Ulj8VcjDOn361jeei0g3Ln6TZbmad1GTu7K_ag1bZz0ef1cP8OBq7Dt8bgPEpSaHzEIIXP4AN7Am0cRexRKYmDIORS8pGgJxWKPcTgEKEx7w-ssjY2:1o8i3o:KTWNK0-JfplBXBTIUGJRL9JhvOss8il28sID4TkhGP4	2022-07-19 12:53:48.799605+00
oky628534igw9wt1wl7n8ln8mj27505k	.eJxVjEEOwiAQRe_C2pBCywAu3XuGZpgZbNVAUtqV8e7apAvd_vfef6kRt3UatybLOLM6K2_U6XdMSA8pO-E7llvVVMu6zEnvij5o09fK8rwc7t_BhG361uAsdT06mxPHbJw3A3I0kD0A9QEGseSxH4SSiDXAlqLDkLsQCULn1PsDAxU35Q:1o8kGb:AKe_1HZpqz_gPZkrkWS6W12OhcP95ivnm__XTsfGn0U	2022-07-19 15:15:09.107472+00
4nyb8sjhqt9yvq20bq7k0i7ni7tzxj4l	.eJxVjMsOwiAQAP-FsyFd7PLw6N1vIMAuUjWQlPZk_HdD0oNeZybzFj7sW_F759UvJC7CKHH6hTGkJ9dh6BHqvcnU6rYuUY5EHrbLWyN-XY_2b1BCL-PLgAZsjlonZ9wEim1Ms9PAjGnWCIaIkEPOSgMSnBECExplJ0OYxecL_us37g:1o8l4C:gtlsM-dmXpVVSqTjWNQ-FZ_I8TZ0i6AcrXG1uzaGZ88	2022-07-19 16:06:24.824967+00
0atki8yexs8ycslvop02fd68agypjsg9	.eJxVjMsOwiAQRf-FtSHIwAAu3fcbyPCSqoGktCvjv2uTLnR7zzn3xTxta_XbyIufE7swo9jpdwwUH7ntJN2p3TqPva3LHPiu8IMOPvWUn9fD_TuoNOq3RoFkY7FSa2uNRukMFGtQknCJwBoBWSiMRapgtJYxAWYAOoNLxaFj7w_Xjzbf:1o8l7o:_5yaE7Xva7PFvv_7qYaCe1nRqQNkRgpWwaV71v8oDAM	2022-07-19 16:10:08.28984+00
lay65jzmy69uvmre4m6cotoigk06vgzp	.eJxVjEEOgjAQRe_StWnoTG2nLt1zhmaYDoIaSCisjHdXEha6_e-9_zKZt3XIW9Ulj8VcjDOn361jeei0g3Ln6TZbmad1GTu7K_ag1bZz0ef1cP8OBq7Dt8bgPEpSaHzEIIXP4AN7Am0cRexRKYmDIORS8pGgJxWKPcTgEKEx7w-ssjY2:1o8lJh:BlVqK2zyMIyXDzkZ6U7C7RyYMBl9IXzZaUpRWOvqasM	2022-07-19 16:22:25.140834+00
59ohczanfxqzisc8vnh582n4870ud650	.eJxVjMsOwiAQRf-FtSF0sDxcuu83kBkGpGogKe3K-O_apAvd3nPOfYmA21rC1tMSZhYXYUdx-h0J4yPVnfAd663J2Oq6zCR3RR60y6lxel4P9--gYC_f2qvIaKzWxo3IYJ1in70bDCdjKVOG5MhbhMFoQgAPUcXR8TkzswES7w8Ncjh9:1o8lLr:qyK_WfQF8Uxxe37JN9ELxskOXGBj2y0Ld3XPgnJBF5A	2022-07-19 16:24:39.521797+00
bxnbsmmuwppuid1y632gcnbod0s09he5	.eJxVjE0OwiAYBe_C2hAILVCX7j0D-f6QqoGktCvj3bVJF7p9M_NeKsG2lrR1WdLM6qyCV6ffEYEeUnfCd6i3pqnVdZlR74o-aNfXxvK8HO7fQYFevjU6L5GZfRwhZhMsOPJMlMmAFSdiwbIIoQnDNA0OjRujGURMQMwE6v0BP0c5eg:1o8lM1:rCa-AtHUpSYyzjIzgcfiM2woMLezn0cecb06yEaQ76E	2022-07-19 16:24:49.726441+00
pvettyu3vnlznjztuzp12h9z3ggcvn2y	.eJxVjEEOwiAQRe_C2hAoLQMu3XsGwjAztmpoUtqV8e7apAvd_vfef6mUt3VMW-MlTaTOCkCdfkfM5cF1J3TP9TbrMtd1mVDvij5o09eZ-Hk53L-DMbfxW_euE7EDDQiFDEjwIQbsAcXx4KMFa5CkoGHvHTP13LmIAJKDtTEa9f4AE744KQ:1o8lM4:Sqf8KxISX8NYhkICZCzdjQD3hs0GCgSgWBWRwCE1GJ8	2022-07-19 16:24:52.307714+00
pm8jso6pmp73kmphvmnfaawz7pyq9uaf	.eJxVjMEOwiAQRP-FsyF0KQE8evcbyMKyUjWQlPbU-O-2SQ96m8x7M5sIuC4lrD3PYSJxFdaJy28ZMb1yPQg9sT6aTK0u8xTlociTdnlvlN-30_07KNjLvkZtNFjAQUOyniEycCKvNCbniZQb2ezJsyM7kkPth6is1UwZCQyKzxcO1Dh-:1o8lPp:447OM7bfOKrDlT2FpAsiD3ZtYYKrhJdVObRbR0dkHcE	2022-07-19 16:28:45.602674+00
mas7pfjea3w9yksza0vikgnda6jtfrmw	.eJxVjEsOAiEQBe_C2hDk04BL956BNDTIqIFkmFkZ725IZqHbV1XvzQLuWw37yGtYiF2Y9ez0O0ZMz9wmoQe2e-ept21dIp8KP-jgt075dT3cv4OKo85aOqNsBFIai0h4NoYkOKu1dABOWS29gpKSBEIXBVknosKUiwHhi2KfL_DYN4w:1o8lQe:AS5AkOtzml_mf3MARsprLJ81CjosbbdF0qLqhCx4rr4	2022-07-19 16:29:36.274638+00
x7209rarsew2abng1a7uv3xavg6jl8v4	.eJxVjMEOwiAQRP-FsyF0AUGP3vsNZGFZqRpISnsy_rtt0oMeZ96beYuA61LC2vMcJhJX4ZU4_ZYR0zPXndAD673J1OoyT1Huijxol2Oj_Lod7t9BwV62NROcWRNF8JyUIj1owkjekvF-C5BiTo5NBHCWEbM3ZCwmBzTwhUF8vjOmOR8:1o8lWb:eTJh9CB-uNTLu1w6c1hoq-4zwy3QEaGYcxS-2NslTIo	2022-07-19 16:35:45.42965+00
ixbppj7ub0a268copwy90yqawnojmkaw	.eJxVjDsOwjAQRO_iGln-26Gkzxksr3eDA8iW4qRC3J1ESgFTznszbxbTtpa4dVrijOzKgmSX3xJSflI9CD5SvTeeW12XGfih8JN2Pjak1-10_w5K6mVf-ww2eUVEHhQ5540YlERl9kxGCHQ2uAEDkEbpnNbZah0UyIkkWUzs8wX7rTer:1o8lXf:0Gg-T3mXVX1IT7oMO-BdFTAATy6VkltuTpKdp4dA168	2022-07-19 16:36:51.272266+00
oz95123bj7k4ljf7hhrg2vvvpa1l0xqz	.eJxVjDsOwjAQBe_iGlmJ179Q0ucM1q69xgHkSHFSIe6OLKWA9s3Me4uAx17C0XgLSxJX4ZW4_I6E8cm1k_TAel9lXOu-LSS7Ik_a5Lwmft1O9--gYCu9JgUwsTMETNm4QSmeYvaWMo9xVBwzEmoHAKwNTsayHSCTs3okT158vid0OJ4:1o8lad:6KXXINzgbj4rIAatmoGX_yPsIsD8YbNz3DUjQO6Pva4	2022-07-19 16:39:55.880856+00
9pe439739ncx2jgr0a744271u2cco0sd	.eJxVjMsOwiAQAP-FsyGydHl49N5vIMCuUjWQlPZk_HdD0oNeZybzFiHuWwl75zUsJC7CaXH6hSnmJ9dh6BHrvcnc6rYuSY5EHrbLuRG_rkf7Nyixl_F1zpqMmhI7uBlAtqxVsmeVJgUeOGKeSGN0iOSyR_LgiUzKyIoMiM8X_OQ38g:1o8lfK:9XHxm3KtlFkCXJSi13mDXa4FhDyNgEB1UMZnSYmZ16M	2022-07-19 16:44:46.473966+00
22lzc1y2lqwxhmdk0qkxtunuzf43i3e7	.eJxVjEEOwiAQRe_C2hAEpliX7j0DGWYGqRpISrsy3l2bdKHb_977LxVxXUpcu8xxYnVWJ68Ov2NCekjdCN-x3pqmVpd5SnpT9E67vjaW52V3_w4K9vKtHSSB0VI2KAGJHQJ5TzTwEZ3NnAMYDjyADcaHIJAJyNDoLLFhcer9ATDuOPA:1o8lfj:GvnVhE0xRWEsfizUf5dCdbkEky2sCE2qZG0FSMi5smc	2022-07-19 16:45:11.826781+00
sjt6k6ry7h8zxft0ah9yt5d7u5gwis7r	.eJxVjDsOwjAQBe_iGln-rK01JT1nsNY_HEC2FCdVxN1JpBTQvpl5G_O0LtWvI89-SuzK0LDL7xgovnI7SHpSe3Qee1vmKfBD4Scd_N5Tft9O9--g0qh7XYxUhQKIglYmzMqRU9ZCEEqj0bGQTEEBCJ01oQMpYCcOBFpltLXs8wXzsjZ_:1o8lfn:OCbm1WbWjWhFqrv3cJwtoeUT6ZBA33Ob2TVfQWtprX4	2022-07-19 16:45:15.254328+00
kkhip5pxzh7wzx0kgutxcwd5qtm512a4	.eJxVjMsOwiAQRf-FtSFCGTq4dN9vaIZhkKqBpI-V8d-1SRe6veec-1IjbWsZt0XmcUrqotCr0-8YiR9Sd5LuVG9Nc6vrPEW9K_qgix5akuf1cP8OCi3lW59TZ5xDCOwYXAgYoicOgpEyZEGTTGSG3mNyvUW0ADbnLBKoy8Co3h8IpDhv:1o8lmO:bvscNf13YnrDK9FoA0snGxh7IP5KAPU7vEEH_t0CcSc	2022-07-19 16:52:04.964589+00
e7jtmhx14s1d172aqi5d8znrv2zm2b9s	.eJxVjDsOwjAQBe_iGlnLxl9Kes5gre01DiBHipMKcXcSKQW0b2beWwRalxrWznMYs7gIZ8Xpd4yUntx2kh_U7pNMU1vmMcpdkQft8jZlfl0P9--gUq9bjboULoMihEygvSXjFKICh64MEZN2G3dQsvIWMhprFKA5J9SeC6P4fAEAxTeJ:1o8lnB:wj_KMmGqh-Mb05lo5i54a7JDl7quSVpXZFLjgdFPQyA	2022-07-19 16:52:53.68801+00
p6ywcueoop4d4dauevx434aa9pjf34on	.eJxVjEEOgjAQRe_StWkslOng0j1naP50iqAGEgor492VhIVu_3vvv0zEtg5xK3mJo5qLYTan31GQHnnaid4x3Wab5mldRrG7Yg9abDdrfl4P9-9gQBm-dUZFHr3nNrEHyPXSUHWWDFVyqLVNTc0k6nYiCFBOtRPyIVRMMO8PLyI4xg:1o8lpw:j1yFNPG9-6IP5520dVT1EVjWi86NF7-Kbd2hsLyfCB8	2022-07-19 16:55:44.196373+00
xkpx14jbkp6huai039ne2bqtj1x0b05f	.eJxVjDsOwjAQBe_iGlnrjeMPJT1nsNbrFQ4gR4qTCnF3iJQC2jcz76USbWtNW5clTUWdVYjq9Dtm4oe0nZQ7tduseW7rMmW9K_qgXV_nIs_L4f4dVOr1W4OM0RvgwVq2hYqzhtkJGUcCQ8yWssWAAbygeMaIBEUAPSG5UUi9PwmxOB8:1o8lqC:YM9DVMv0sLJhZGxWCuchJ_NgjoYFDrHKDzAa2UrCNsQ	2022-07-19 16:56:00.208467+00
n84b8td6bsma30w5eee2u2otgwn0208b	.eJxVjDsOwjAQBe_iGlnrT2xMSZ8zROvdNQkgW8qnQtwdIqWA9s3Me6kBt3UctkXmYWJ1UQnU6XfMSA-pO-E71lvT1Oo6T1nvij7oovvG8rwe7t_BiMv4rR10hjMX9NmHFC133mQbHRYfBADZsTiyRkoshARYgu3EhHAGopSien8AGLg4iQ:1o8lr9:FO3bH4EFaKZEB8X2E0sOmA8StTxzcNoEgd3uI6JD3XA	2022-07-19 16:56:59.869995+00
kjxn8a6fu61j3covif8i8brjzcg0st82	.eJxVjDkOwjAUBe_iGlmx45WSPmeI_BfjALKlLBXi7iRSCmjfzLy3GNO2lnFbeB4nElcRlbj8jpDwyfUg9Ej13iS2us4TyEORJ13k0Ihft9P9OyhpKXvdaw6mVxmdso4dIzi0EbzP0QdgnSMb40gh7SKwz6B0h5QDudyhseLzBRofOOU:1o8lrG:eiU22O--4nz5e9kstws313hx9IizIDJasB9KevNHXq0	2022-07-19 16:57:06.872082+00
6m7me2hy405wc8yaju12mp7trm9x0gqp	.eJxVjMsOgjAQRf-la9O0lD506Z5vaO7MFEENJBRWxn9XEha6veec-1IZ2zrkrZYlj6Iu6tyo0-9I4EeZdiJ3TLdZ8zyty0h6V_RBq-5mKc_r4f4dDKjDt2brWKwRz-R8cMxeYg9JFmxcBBobraS-bWIiA8AnbksQBEoEI616fwAomzkF:1o8lsv:-nQrGzpOH2HkcVLoEpvQmBpROCmbOcwnUlTm7HTswkM	2022-07-19 16:58:49.465089+00
tenzlsu6hglhyfnxv1szg0i0rlztvfqw	.eJxVjDsOwjAQBe_iGln476Wkzxks27uLA8iR8qkQd4dIKaB9M_NeIuVtbWlbaE4jiosAI06_Y8n1QX0neM_9Nsk69XUei9wVedBFDhPS83q4fwctL-1bRw0ciyZGHawDhRCInY6KPLrAZ09EsbLVHJRTCjgEj2BRczUGwIv3Bw1nN-o:1o8luQ:72psf8GgySWfy2QWQUIAtOuisvTgmHkfDmbOBaIOWgQ	2022-07-19 17:00:22.610905+00
kks1yv8akdcdge3i5yaeesxcp1h6ic6m	.eJxVjEEOgjAQRe_StWnamQodl-45QzPtDIIaSCisjHdXEha6_e-9_zKJt3VIW9UljWIuhoI5_Y6Zy0Onncidp9tsyzyty5jtrtiDVtvNos_r4f4dDFyHb-0wgzKUthVyDQgpYiwsoA30uWCM6PHsg28oSCBypOygJ59BGENv3h8BDjep:1o8lwP:DrT1XVu39yuKQzkoJnYcg2qcqBIAdBevTYeheMnYAVQ	2022-07-19 17:02:25.727666+00
pibuy1x0hxiv321l8lsc0rpuiqg6vt6c	.eJxVjEEOwiAQRe_C2hBgOiAu3XsGAsNUqgaS0q6Md7dNutDtf-_9twhxXUpYO89hyuIiPIrT75giPbnuJD9ivTdJrS7zlOSuyIN2eWuZX9fD_TsosZetVo4INWqDlBSfIdsE2lscDVpvQVt2nDHBYBIxKwcDR2DQ6GGkLRCfL_PBN6o:1o8lxV:rta2-cnt5KeAC4-m4u_rBrn7Rn9Z9uSZTt5LEF1oKQo	2022-07-19 17:03:33.585428+00
vlnwmhxdd9f9k0fm7xgj9w3179c1htgp	.eJxVjEEOwiAQRe_C2pBCERiX7nsGMsCMVA0kpV0Z765NutDtf-_9lwi4rSVsnZYwZ3ERYMXpd4yYHlR3ku9Yb02mVtdljnJX5EG7nFqm5_Vw_w4K9vKtDRAxD0wqg_fsYEC0o1NGeTTeKUAPMZFmp10ck05oISkTmQjPI4J4fwAfKzi5:1o8lyC:ljLlbFiO-3BeS-hEuR29dM6-g64Wb67Xo8Ux2A4Z-JU	2022-07-19 17:04:16.189251+00
ua8veamyjuo00jmzudwa3lvnt6e61rfm	.eJxVjMsOwiAQRf-FtSHDS8Cl-34DGRiQqoGktCvjv2uTLnR7zzn3xQJuaw3byEuYiV2Yt-z0O0ZMj9x2Qndst85Tb-syR74r_KCDT53y83q4fwcVR_3WoI0pOqlIpfhERjiIBSgJiBm9lA5MVk7GTAAa01lZYY201jmyKI1j7w8bMTfZ:1o8lyF:ccV6FHbyY1g8sDlMVtgd9Ro82eQlznRxxxR50Hwkv3o	2022-07-19 17:04:19.64133+00
mc6uohx4u2w8n4v65ajfxpabuv8wa3om	.eJxVjEEOwiAQRe_C2pBChwFcuvcMhGGoVA0kpV0Z765NutDtf-_9lwhxW0vYel7CzOIsvBOn35FieuS6E77HemsytbouM8ldkQft8to4Py-H-3dQYi_fGi2D9UieeFA4UgSfHRKAMQqnlIgVaA1k9JQcRD-OA2cPGdCiIXLi_QEBVDfB:1o8m01:pi4BpP8D_Qo_30TX6q8zY1Xy39dhABP5cpzUnOERf40	2022-07-19 17:06:09.130164+00
n2u10dtp7rvqvo2eps20mhuuwwtavcov	.eJxVjDsOwjAQBe_iGlmJfxtT0ucM0e7axgFkS3FSIe6OLKWA9s3Me4sFjz0vR4vbsgZxFd6Ly-9IyM9YOgkPLPcquZZ9W0l2RZ60ybmG-Lqd7t9BxpZ7HU105Dw4A5yGlHgiBm-NJuUSecdI44CjYg3BEqH12uoUAYJKExjx-QIviTi4:1o8m0j:96NeQcikU8i1JQv0-phEBxkz6YUzPnOYFJOz3bgJurU	2022-07-19 17:06:53.246525+00
t89fq807pxnk07hsdbr9bgmtj61ee2zc	.eJxVjEEOwiAQRe_C2pCBoQou3XsGMgOMVA1NSrsy3l2bdKHb_977LxVpXWpce5njmNVZGQB1-F2Z0qO0DeU7tduk09SWeWS9KXqnXV-nXJ6X3f07qNTrtwbxhgkwOSOSBiZhCFCOjIETGkErwYH3uZB1xgOFkqxFZjucECmo9wdA8zh2:1o8m1W:rEw_8B16gANMJ0L7DLvsfbtQrAySyK5ER3gW6sQZCZo	2022-07-19 17:07:42.208224+00
jcnafsob59w0uh33cwddyzrucq4w3k3l	.eJxVjEEOwiAQRe_C2pCZAUFcuu8ZmoFBqRpISrsy3l2bdKHb_977LzXyupRx7XkeJ1FnhYDq8LtGTo9cNyR3rremU6vLPEW9KXqnXQ9N8vOyu38HhXv51t6RRQsxiCehxJAtRofsTAKgGICRskcxV2uIkkUOJMbCMbEPJ8Pq_QEEnjdC:1o8mBF:J7extvvfiKo_RH60r5nNJPK7jIqq4RE9aLN6-x_c_Ps	2022-07-19 17:17:45.433216+00
yyz55a1tbx0dkw52jbkpbl55m0nq07ks	.eJxVjDsOwjAQRO_iGln-xB8o6TmDtd5d4wBypDipEHcnkVLAlPPezFskWJea1s5zGklchFZGnH7bDPjktiN6QLtPEqe2zGOWuyIP2uVtIn5dD_fvoEKv2zpTcRqJXDaD2gKQY2ECjbEEcn7wrLQnKmcs4ILSNlhk702xEcmy-HwBWQs5RA:1o8mBr:fSqxCURgN-hvBxTBhcq1ftY-JcewH5HuhtNVEmSGElM	2022-07-19 17:18:23.848191+00
9j8fqsbksmmaagb7e10ulx5m60gffoky	.eJxVjDsOwjAQBe_iGlm7YPyhpM8ZrF2vjQPIkeKkQtwdIqWA9s3Me6lI61Lj2vMcR1EXhXBSh9-VKT1y25Dcqd0mnaa2zCPrTdE77XqYJD-vu_t3UKnXb83JHYMPKGTMmcE5SIBUnHdQ0NpEWTIWCmAzJiuFmQz6UKxwQS9OvT8x_zj4:1o8mG0:-sFIGnNEH0zRAB_ExRSQ5IP-fbAHYNo5Y2XEdewvysY	2022-07-19 17:22:40.89078+00
qdr193lf92dhgh144zyc0a3ufg0jmjn4	.eJxVjDsOwjAQRO_iGlnelYNtSnrOYG0maxxAiZRPhbg7iZQCminmvZm3ybIuNa-zTrnvzMWQ8-b027aCpw476h4y3EeLcVimvrW7Yg8629vY6et6uH8HVea6rUtqAUecEmmkwpGbswfAWwbPkgIFRz4AguLRFCkcIqDKTgOR-XwBJx44YQ:1o8mJa:E1yQRgVHr2fbWo9t_9XnVS_aEKHPAgV4W_bAEuR-l1k	2022-07-19 17:26:22.589521+00
d4qeo8y76s9w2a1j5r7v418g35xvrok8	.eJxVjEEOwiAQRe_C2hCgMwFcuvcMZIBBqgaS0q6Md9cmXej2v_f-SwTa1hq2wUuYszgLrVCcftdI6cFtR_lO7dZl6m1d5ih3RR50yGvP_Lwc7t9BpVG_NUwWHFgAq9AzUMmAhsnrWChmZDRJ2RIZtNcY2RMlO1lEj4YMOSfeHx0TOBI:1o8mKn:4T8JqzU72VCsMMSy9qGMlfd_WacwNc23kmXkvtoT6fM	2022-07-19 17:27:37.031261+00
fn8084mxs47zbbwfu4r8j4240ew5o15d	.eJxVjDsOwjAQBe_iGllJ_NmYkp4zWLveNQ4gR4qTCnF3iJQC2jcz76UibmuJW5MlTqzOqu-8Ov2uhOkhdUd8x3qbdZrrukykd0UftOnrzPK8HO7fQcFWvrW12TH0JMl7AEM5wYAOSMaAfhDAjh2G7AQ4j2CdiLAYCN5kYzyRen8ARwg5Hg:1o8mL5:WVbuPZakGHgf7nSnly4COcPPLNDHq0KZj5xqQiugt5A	2022-07-19 17:27:55.74616+00
3fqreifipt50j7917n8hrk91mh165w5e	.eJxVjDsOwjAQBe_iGln2-htKes5g7dprHECJFCcV4u4QKQW0b2beSyTc1pa2zksaizgLrYI4_a6E-cHTjsodp9ss8zyty0hyV-RBu7zOhZ-Xw_07aNjbt_ZQMzmMQACIJoO21gYe2BguChwReo5RUfZKFzfUqGEIRoXqtCUVxfsDLog3xw:1o8mR7:JAUwho6Y4pEW-BOSh6oLFX0U2rxVeVwzOoDKUWrDwRw	2022-07-19 17:34:09.875353+00
6v0ewsto7itdr2496nzkt6bn0bhh06or	.eJxVjDsOwjAQBe_iGlmJfxtT0ucM0e7axgFkS3FSIe6OLKWA9s3Me4sFjz0vR4vbsgZxFd6Ly-9IyM9YOgkPLPcquZZ9W0l2RZ60ybmG-Lqd7t9BxpZ7HU105Dw4A5yGlHgiBm-NJuUSecdI44CjYg3BEqH12uoUAYJKExjx-QIviTi4:1o8mZC:hnLTCc4sgECtcLc5fj7xc7VVooLNogShLpW2Kjwjpxs	2022-07-19 17:42:30.396024+00
1gxmtancxekjlg7pmgg9ilf47mn9jijz	.eJxVjEEOwiAQRe_C2hBoYQou3XsGMsOMUjU0Ke3KeHfbpAvd_vfef6uE61LS2mROI6uzsiao0-9KmJ9Sd8QPrPdJ56ku80h6V_RBm75OLK_L4f4dFGxlq8UHseTB0A05Bod9hhhoyM6hePBiHXNAtpvROXAEiNlE8BFsh0OvPl8-Wjg6:1o8mem:3Elz0RzOQsSYVHxs4pKghX1rH_VNdBJ9A9xeIZuE5IY	2022-07-19 17:48:16.303877+00
9h5dakhg6vkqm2h1fr6mgyj0f06gn0pz	.eJxVjEEOgjAQRe_StWnoTG2nLt1zhmaYDoIaSCisjHdXEha6_e-9_zKZt3XIW9Ulj8VcjDOn361jeei0g3Ln6TZbmad1GTu7K_ag1bZz0ef1cP8OBq7Dt8bgPEpSaHzEIIXP4AN7Am0cRexRKYmDIORS8pGgJxWKPcTgEKEx7w-ssjY2:1oD4yM:24MXYpZj20dwVB-m9wloxkM6xElanlmcXEKj1kUJQUI	2022-07-31 14:10:14.731351+00
utezxdrw1ut5tt42pquqv1filmaa9aqx	.eJxVjEEOwiAQRe_C2pAB2jK4dO8ZCDCDVA0kpV0Z765NutDtf-_9l_BhW4vfOi9-JnEWCpw4_a4xpAfXHdE91FuTqdV1maPcFXnQLq-N-Hk53L-DEnr51ilGtIYpJxesATXiSNOgOWsNaSCn0FoNE6IhRDApqIisDRulAAiyeH8AKV83oQ:1oDOpr:fEjY4vQ5kX06cEEH0X06sW94dCcxNQtpXRMN4fbx8V0	2022-08-01 11:22:47.423762+00
w01jlte6ztui0ne1aizo571iokvb03l6	.eJxVjEEOgjAQRe_StWnoTG2nLt1zhmaYDoIaSCisjHdXEha6_e-9_zKZt3XIW9Ulj8VcjDOn361jeei0g3Ln6TZbmad1GTu7K_ag1bZz0ef1cP8OBq7Dt8bgPEpSaHzEIIXP4AN7Am0cRexRKYmDIORS8pGgJxWKPcTgEKEx7w-ssjY2:1oE597:nLu-F10tgJK0N6Jz8j4rDfpFWDIoC4Y9dWvz6K7hPaQ	2022-08-03 08:33:29.538649+00
e3hnyij6y7l6xt962p3sl44zwz6k9fod	.eJxVjEEOwiAQRe_C2pBCywAu3XuGZpgZbNVAUtqV8e7apAvd_vfef6kRt3UatybLOLM6K2_U6XdMSA8pO-E7llvVVMu6zEnvij5o09fK8rwc7t_BhG361uAsdT06mxPHbJw3A3I0kD0A9QEGseSxH4SSiDXAlqLDkLsQCULn1PsDAxU35Q:1oE6IK:Q2cvmrsCHs-pbpU_IConrikiD4SZvMU8DYDhkpvBahM	2022-08-03 09:47:04.781691+00
cfiq3fydqhrchkd20v6euxivgn5arycb	.eJxVjEsOwjAMBe-SNYpiJ20Sluw5Q-XaLimgVOpnhbg7VOoCtm9m3st0tK2l2xadu1HM2QB4c_pde-KH1h3JneptsjzVdR57uyv2oIu9TqLPy-H-HRRayrf2mH2jbR-caBQCxEaZqI0xspOUOfHACDKQeh9zcjEEJKAhIDtoxLw_MU84WQ:1oEYbp:oyGKQkj5RAJ_FH3wGjrJYTWk2CUq2JQzFA67RC1_yQk	2022-08-04 16:01:05.10766+00
cnaqbg84ce4797mufku4ddjlmeicq3s2	.eJxVjDsOwjAQRO_iGll2bGsxJT1niGa9GxJAsZRPhbg7iZQCypn3Zt6mxbr07Trr1A5iLsb7aE6_LaM8ddyRPDDeqy11XKaB7a7Yg872VkVf18P9O-gx99ua1ItycVEp5CSSSoO8Be7cWeF8ASQQU8pdAhC9YwoEalKKnAXm8wVUmjkZ:1oEYj3:q4fj4RmdsyY-FKprG4WVntr8F-HZ_4tfXj6kwUj9kA0	2022-08-04 16:08:33.558365+00
3b7vokwfla9hgjehivgrrobrpi6lb27j	.eJxVjsEOwiAQRP-FsyEUWKQevfsNZNkFqRqalPZk_Hdp0oNe582bzFsE3NYStpaWMLG4iGEAcfpNI9Iz1R3xA-t9ljTXdZmi3CvyoE3eZk6v69H9GyjYSreBSSnN0VhFAOg9e8MOojtbTCobnVHFrLN1msmM3mTXv_CYqCtgSHy-Lxg4Ww:1oEYmC:_Tc6_41OdM0J2-_Eb29UVSFGoN7xeio8kHDV4rcIB8Y	2022-08-04 16:11:48.32157+00
3a4avjcxwvnz0vyeohgfdheeqcih19t0	.eJxVjMsOwiAQRf-FtSFDi8zg0n2_gQwM2KqBpI-V8d-1SRe6veec-1KBt3UM25LnMIm6KGOcOv2ukdMj1x3Jneut6dTqOk9R74o-6KKHJvl5Pdy_g5GX8Vt7NIggkblQBAIg44uIcb5QtpCwAINQcT46kDPlrusteSmIaFPv1fsDKcs3-A:1oEYnE:IhVdh0RGc2PjXdIevqyxT9k2SUe3yuhc1qr3jWXPTNo	2022-08-04 16:12:52.560531+00
743jiq1cjwz5rnzco2jmv8sim32j70fv	.eJxVjEEOwiAQRe_C2hBBYKhL956BzDBTqRpISrsy3l2bdKHb_977L5VwXUpau8xpYnVWxoA6_K6E-SF1Q3zHems6t7rME-lN0Tvt-tpYnpfd_Tso2Mu3JgHJ7EL0EKy3OACOzuUTRsciR7AmGPQRybsYKMBA3pOxBgIzA43q_QEvKThI:1oEYo4:q898Z4L9rHS08nsshzaoAjGCGzsbBNs3TrQ2FuALYME	2022-08-04 16:13:44.431418+00
7n06yvy3og1mn4f42x021a8i8sizko16	.eJxVjMsOwiAQRf-FtSEw8pi6dN9vIMBMpWogKe3K-O_apAvd3nPOfYkQt7WErfMSZhIXoTWK0--aYn5w3RHdY701mVtdlznJXZEH7XJsxM_r4f4dlNjLt7YWjSK02p8REsEAWnnDE2W0ygO7DBoZidxEZF1knSxgNjBEkwyxeH8ADH04FA:1oEYoa:s1v6uqWGPIMgrQXc5ZaqSRNwiBWi4K0WF_2cVvXKctM	2022-08-04 16:14:16.257553+00
b144we7k4z39yyl7wx8d1j1n10tpzthm	.eJxVjMsOwiAUBf-FtSFQsBSX7vsNzeU-pGogKe3K-O_apAvdnpk5LzXBtuZpa7xMM6mLsjaq0--aAB9cdkR3KLeqsZZ1mZPeFX3QpsdK_Lwe7t9Bhpa_tQHv2HtnzpCIDQk56bsQKQ4-kR24MwFSYKZAFER6EIcI6EUscrLq_QFSUzoV:1oEYwk:Wst4sdeZot97xc22v1TM1uRNj59PCSQyelgTKnxQxFk	2022-08-04 16:22:42.28557+00
4d0c1wyksqf2c0fhqke2xb3jigmzlp5k	.eJxVjMsOwiAURP-FtSG8atGl-34DuQ-QqoGktCvjv0uTLnQ1yZkz8xYBtjWHrcUlzCyuQhslTr8UgZ6x7BU_oNyrpFrWZUa5K_Jom5wqx9ftcP8OMrTc10NM3jtjFTJ5BLCUKA3EQBdWiqxTPRwiAbOykLQZkzvbEU1H2kbx-QJjBjmy:1oEZ0o:K2-s3tROzITCjcJlOUus6XEacEjbO_yb1lZsxBoEF1Y	2022-08-04 16:26:54.908521+00
z7k6nn27cqf1iws0ckd20hzmyc5lprop	.eJxVjMsOwiAQRf-FtSEww8O6dN9vIAMMUjU0Ke3K-O_apAvd3nPOfYlA21rD1nkJUxYXoUGL0-8aKT247Sjfqd1mmea2LlOUuyIP2uU4Z35eD_fvoFKv31oZXTI4axOxTwkBoUSnwDiNJgMiDoY9sMYzInNxXkcawHnPKkay4v0BDgQ3kw:1oEZ3I:4Nj-ofYYgRqnstx-bDTrmuxHiUT_73ZQuodGXw00VZc	2022-08-04 16:29:28.728168+00
1gk9q1qws7snqys9jno5rhdlxr953cwj	.eJxVjDEOwjAMRe-SGUXYieKWkZ0zRE7skgJKpaadEHenlTrA-t97_20ir0uJa9M5jmIuBhDN6XdNnJ9adyQPrvfJ5qku85jsrtiDNnubRF_Xw_07KNzKVqs_k2ZFYSQPGRU8utBBVpEhqELIRMI-BUDHTnqi1A8oHTG6zTWfLz2ROF0:1oEZCg:2FJAJccPYbXkFx92isoUqs9r5jCDjfASZrzh6KC1Gqo	2022-08-04 16:39:10.726511+00
r1fadwo9ngexux9x5psgw4n9e49glsdg	.eJxVjDkOwjAUBe_iGlnxmpiSnjNEfwsOIFuKkwpxd4iUAto3M--lRtjWPG5NlnFmdVbGOnX6XRHoIWVHfIdyq5pqWZcZ9a7ogzZ9rSzPy-H-HWRo-VsH7gWh996JJEE_YIhMQ-IgMbpAnieDBhx2tpsMWCMpkHPeEsQpEKj3B0iEOOw:1oEZDZ:1xKJaMs-SvNS_XPeTdW7o9CcZ8DbuKz5T8cFlTvk6mc	2022-08-04 16:40:05.170824+00
8ucaqhoauwsc38z60nztds689lywn6bj	.eJxVjDsOwjAQBe_iGlnOYhtMSZ8zWPsLDiBHipMKcXeIlALaNzPvZTKuS8lr0zmPYi6mA28OvyshP7RuSO5Yb5PlqS7zSHZT7E6b7SfR53V3_w4KtvKto4-UOsSYWIMTr-jwLATokvpwTBIYfMQA4hwNDBBBT-gish8CEZv3BzgeONg:1oEZGI:LzFASRlCPw7Sqknllf1HH55rhx-fTIJLLVyVDDepbXM	2022-08-04 16:42:54.145319+00
plrgcr0e8mdqsvutof9zf5p89t8hojlk	.eJxVjEEOwiAQRe_C2hBnCgx16d4zkCkMUjU0Ke3KeHfbpAvdvvf-f6vA61LC2mQOY1IXBWjV6ZcOHJ9Sd5UeXO-TjlNd5nHQe6IP2_RtSvK6Hu3fQeFWtrUVMNYJ9xEcGUyRcgTpGSESboDlzJQ7JEuOferIZPYoyXoAyw7V5wsmaTfb:1oEZGN:_fZyGqP-8w3BYl6OQSgBSfsPuD1tj_Cu_U7vmAyhVaU	2022-08-04 16:42:59.075506+00
6vvggsxnkg868799lhbenccbz04ofhgy	.eJxVjDsOwjAQBe_iGln-hfVS0ucM1tpe4wBypDipEHeHSCmgfTPzXiLQttawdV7ClMVFaHMWp981Unpw21G-U7vNMs1tXaYod0UetMtxzvy8Hu7fQaVev7VjtqjKQLEQOmClCw6FrAWNOQGiN8m4mECztyZlYA2oolYesnOA4v0BNsg39A:1oEZGy:JveWKXifmfEuWrr3y5MZPbnbdrPW2MGj48dUlY9fq0I	2022-08-04 16:43:36.014006+00
5izqidsubolz4ji1cfq814m3lhw3gvem	.eJxVjMEOwiAQRP-FsyHLUkE8eu83kAUWqRpISnsy_rtt0oPeJvPezFt4Wpfi186zn5K4CoVWnH7bQPHJdUfpQfXeZGx1macgd0UetMuxJX7dDvfvoFAv29pqDkAagOOWrEJFQcczIoScBgI04Ew0BERszZAu2emEnBmAHAYjPl82ujic:1oEZLI:j7-0dnh-tZckcMSkOnIt-_FXlGYjMeOg99N5NblqyX4	2022-08-04 16:48:04.423796+00
z2wgvm262n4yho4no2s7qnwnxty5hvui	.eJxVjMsOwiAQRf-FtSEwUB4u3fsNBIZBqgaS0q6M_65NutDtPefcFwtxW2vYBi1hzuzMJDh2-l1TxAe1HeV7bLfOsbd1mRPfFX7Qwa890_NyuH8HNY76rQWiVSUWYTUgeC1U9JN0QhF6k0XSYIGUUsnpRDQZCUWSlmilAWdTYe8PGb43ng:1oEZLh:M-bPmPS21cE4dmXosQRplA2ab6eWQDYn6aqR8Xug4Zk	2022-08-04 16:48:29.107914+00
aqlhxia3v2czbc765fkne38usf1wd5b1	.eJxVjEEOwiAQRe_C2hCYGQRcuvcMhMIgVUOT0q6Md7dNutDtf-_9twhxXWpYO89hzOIiNHhx-l2HmJ7cdpQfsd0nmaa2zOMgd0UetMvblPl1Pdy_gxp73WqTwSnijFQ0e0BltVZwpojggJNGy8gARXkgZ7FsDKMiZ5DIsM_i8wX1XjZ-:1oEZS6:jmsq6ei-B7NRj1jQkevt8_kBiGCjvtUVpvz1unTPcCo	2022-08-04 16:55:06.173332+00
rh9n85n4ani6zcc2p22v447xeoh79xx2	.eJxVjMsOwiAQRf-FtSEwdHi4dO83NAMDUjU0Ke3K-O_apAvd3nPOfYmRtrWOW8_LOLE4C22UOP2ukdIjtx3xndptlmlu6zJFuSvyoF1eZ87Py-H-HVTq9Vt7A-A4GPRKW8DAQ0B0NCAjotWQGHxUJUBUyNYNoLzLQFxKVJpMEe8P4_03GA:1oEZT5:-Q6sapzHyRNdApF_bBY4gEaPCVKfsEUVFC13gJRgFpQ	2022-08-04 16:56:07.145895+00
ftio8344hmlg5l10513783wz98wnayg8	.eJxVjEEKwyAQAP_iuYira5Qee-8bxHVNTVsUYnIK_XsRcmivM8McIsR9K2HveQ0Li6sAA-LySymmV65D8TPWR5Op1W1dSI5EnrbLe-P8vp3t36DEXsaYZ5W8wey0M95ZbSHNeWIgm0hHMAosTcogxqQzgvKOPaJVyMTARny-E6Q3hQ:1oEZT5:3t290r5-aeslzaujtb4WC8nET-1NBeTA5WrZVCxQ_cY	2022-08-04 16:56:07.593107+00
dxdt8z44wo1exil2gida7i95xd0s7uyw	.eJxVjEEOwiAQRe_C2pAMA1JcuvcMZGAGqRqalHZlvLtt0oVu33v_v1Wkdalx7TLHkdVFARp1-qWJ8lParvhB7T7pPLVlHpPeE33Yrm8Ty-t6tH8HlXrd1gEhZAFJ4JkHJM-WHdJgxZtUSgE2gaC45ChYDGg2DFbOhm0o6El9vjySOHA:1oEZlC:MtGt3giyd8sgjd-43k1k81FV7SOQE-m5sM9NKG1pQUc	2022-08-04 17:14:50.377697+00
vetl3lpnh5i4lhvoj0bf7l7yw1y28fyg	.eJxVjMsOwiAQRf-FtSE8CliX7v0GMsMMUjWQlHZl_HfbpAvdnnPufYsI61Li2nmOE4mL0NaK0y9FSE-uu6IH1HuTqdVlnlDuiTxsl7dG_Loe7d9BgV629QgeCQ0woGK0Jp0doNPI2Q_OWwsGNQegwIOhrLJXyeeRfE4ccAPi8wVpGDoF:1oEZq7:M4PsWQ5rcZufyEKwKXiLpccV8xPwew43XG7UgtfZCFQ	2022-08-04 17:19:55.833559+00
b8ocann3zoa21izjuy2yz1e2dkpcdcrj	.eJxVjEEOwiAQRe_C2hBmmAJ16d4zEGAGWzVtUtqV8e7apAvd_vfef6mYtnWIW5MljqzOCiyp0--aU3nItCO-p-k26zJP6zJmvSv6oE1fZ5bn5XD_DobUhm-NCOKZMdmQyaAgsHeBIVNXck8ZyKMxvWVy6KiKreIDGB9YalcE1PsDFfI30Q:1oEa4n:1hRMYbAzXp6dmGV0lcapjd6CRJE0--T5_Vgqjm2mDWs	2022-08-04 17:35:05.240962+00
swygc5ds5d1wo73fyankwekuo5kltf9m	.eJxVjMsOwiAUBf-FtSGl5CK6dO83kPtCqgaS0q6M_65NutDtmZnzMgnXpaS165wmMWfjPJjD70rID60bkjvWW7Pc6jJPZDfF7rTbaxN9Xnb376BgL99aB44ooxxVQ2QPypE8U2AnkSEDCEBmzhoIMqrTAIF4JMc6RO9O5v0BdGk57g:1oEaJE:oUM4EzyXjRlq6PUiDpyA8-6lfjMnb5O8AkeBiZqfgcw	2022-08-04 17:50:00.199247+00
b2c8zx2rem01h3ic20fomcnwmsv8xjmn	.eJxVjMEOwiAQRP-FsyGly8Li0Xu_gQALUjVtUtqT8d9tkx70OPPezFv4sK3Vby0vfmRxFQqMuPy2MaRnng7EjzDdZ5nmaV3GKA9FnrTJYeb8up3u30ENre5rNIoQUOtMJTkmLgRxTw5t0khgHBL1QGijUaxKLqA71fWaDUAhKz5fAy826Q:1oEaue:NnsX7SvF0853TWtzmHI5OSrr9765e8b7eQP4dqcnNPA	2022-08-04 18:28:40.296314+00
p4dt8h9qoitxc3aatfgzyvv79axxt0mw	.eJxVjMEOwiAQRP-FsyHYrgt49O43EHYXpGpoUtqT8d-VpAc9zGXem3mpELe1hK2lJUyizuo4WnX4bSnyI9WO5B7rbdY813WZSHdF77Tp6yzpedndv4MSW_mufc4EzmaRIXkEBEZDAgM5G8FbPKVMTrIxBoiNOEZxeWQP2INevT9GtziW:1oEb29:xQFP-_2C7z6a2dljf8NrOYRJeL2_o2Jcom6xC78W804	2022-08-04 18:36:25.556264+00
y5ux5pnvda0a7az3ui0zuv4n48g4y0ra	.eJxVjMsOwiAUBf-FtSFAody4dO83EO4DqRqalHZl_Hdt0oVuz8ycl0p5W2vauixpYnVWdgB1-l0x00Pajvie223WNLd1mVDvij5o19eZ5Xk53L-Dmnv91uC8LSKMTtgUZhQiKkDWkYviA2CEkK0J3rAxGH0Zo4uFBhoRLHj1_gBmdzj2:1oEbE1:SleYM3fNoG4jnLG74mJ-1ttn1V3PO5XvTJVugJ4T02k	2022-08-04 18:48:41.487494+00
c5ng5qve2286qcwp6rnmx6nv9sws9d20	.eJxVjDsOwjAQRO_iGln-ZmNKes5grXcdHECOFCcV4u5gKQV0o3lv5iUi7luJe8trnFmchbZBnH7bhPTItSO-Y70tkpa6rXOSXZEHbfK6cH5eDvfvoGAr3zUBW-WNN5YIXE9oSYNmdAYAnAX2k87G2THpnGDSCGrENISgfBiMeH8ABt03FQ:1oEbSX:KtlmqgCnxnO2oM8u1cBdIBQwiv5HDihIJzT5ZMLvt5Q	2022-08-04 19:03:41.119984+00
rwxew0xjorq5a6r3cpbv66zks28134ak	.eJxVjDsOwjAQBe_iGln-ZWNT0nMGa71e4wBypDipEHeHSCmgfTPzXiLitta4dV7ilMVZaKfE6XdNSA9uO8p3bLdZ0tzWZUpyV-RBu7zOmZ-Xw_07qNjrt8ZQwJbMo2KbjB4AXSFGcqMnMm4wRTNbB8qzVsFTNsA-BGZI2toE4v0BRts4oQ:1oEbSa:ecQwurdkLCIA12khQtK-kKAaAqj8Z8n6dJrJMy8uceY	2022-08-04 19:03:44.100521+00
achv1h1g3sbxq0pg27xd2kl44hnaqqt4	.eJxVjMsOwiAQRf-FtSEww8O6dN9vIAMMUjU0Ke3K-O_apAvd3nPOfYlA21rD1nkJUxYXoUGL0-8aKT247Sjfqd1mmea2LlOUuyIP2uU4Z35eD_fvoFKv31oZXTI4axOxTwkBoUSnwDiNJgMiDoY9sMYzInNxXkcawHnPKkay4v0BDgQ3kw:1oEbtF:j98v3C-M5ewUF33L-3R99nKzpZuYqa2EPptcwzevjgQ	2022-08-04 19:31:17.247107+00
\.


--
-- Data for Name: flags_flagstate; Type: TABLE DATA; Schema: public; Owner: twistdbadmin
--

COPY public.flags_flagstate (id, name, condition, value, required) FROM stdin;
1	CAN_SIGNUP	boolean	False	f
\.


--
-- Data for Name: song_signup_groupsongrequest; Type: TABLE DATA; Schema: public; Owner: twistdbadmin
--

COPY public.song_signup_groupsongrequest (id, song_name, musical, request_time, requested_by_id) FROM stdin;
13	Satisfied	Hamilton	2022-06-17 13:23:13.657862+00	1
14	The Room Where It Happens	Hamilton	2022-06-17 13:23:37.170961+00	1
15	Guns and Ships	Hamilton	2022-06-17 13:23:55.525473+00	1
16	My Shot	Hamilton	2022-06-17 13:24:08.637555+00	1
17	Story of Tonight	Hamilton	2022-06-17 13:36:17.567943+00	1
21	RIght Hand Man	Hamilton	2022-06-17 13:37:08.92853+00	1
22	The Schuyler Sisters	Hamilton	2022-06-17 13:38:41.731694+00	1
23	One Day More	Les Mis	2022-06-17 13:44:32.483486+00	1
24	Do You Hear the People Sing?	Hamilton	2022-06-17 13:45:15.46185+00	1
25	Deliver Us	Prince of Egypt	2022-06-17 13:49:31.846526+00	1
26	The Plagues	Prince of Egypt	2022-06-17 13:50:16.928587+00	1
27	Look Down	Les Mis	2022-06-17 13:50:58.353951+00	1
28	What Is This Feeling?	Wicked	2022-06-17 13:53:20.492603+00	1
29	The Wizard and I	Wicked	2022-06-17 13:54:46.47841+00	1
30	Popular	Wicked	2022-06-17 13:55:48.869612+00	1
31	All That Jazz	Chicago	2022-06-17 13:57:04.370982+00	1
32	Cell Block Tango	Chicago	2022-06-17 13:58:23.007772+00	1
33	When You're Good to Mama	Chicago	2022-06-17 13:59:51.091047+00	1
34	Both Reached For the Gun	Chicago	2022-06-17 14:05:29.83735+00	1
35	Sincerely Me	Dear Evan Hanson	2022-06-17 14:10:53.801421+00	1
36	Sucks To Be Me	Avenue Q	2022-06-17 14:11:17.396276+00	1
37	If You Were Gay	Avenue Q	2022-06-17 14:11:38.895796+00	1
38	The Internet Is For Porn	Avenue Q	2022-06-17 14:12:11.929264+00	1
39	Loud As The Hell You Want	Avenue Q	2022-06-17 14:12:29.749317+00	1
40	You Can't Stop the Beat	Hairspray	2022-06-17 14:14:41.863363+00	1
41	Welcome to the 60s	Hairspray	2022-06-17 14:17:30.697528+00	1
42	Good Morning Baltimore	Hairspray	2022-06-17 14:17:53.232943+00	1
43	The Nicest Kids In Town	Hairspray	2022-06-17 14:18:13.162867+00	1
44	Under the Sea	The Little Mermaid	2022-06-17 14:19:37.044311+00	1
45	Can't Wait To Be King	The Lion King	2022-06-17 14:20:02.739519+00	1
46	The Circle of Life	The Lion King	2022-06-17 14:23:02.864116+00	1
47	Hakuna Matata	The Lion King	2022-06-17 14:29:27.179631+00	1
48	Be Out Guest	Beauty and the Beast	2022-06-17 14:31:37.730461+00	1
49	Rent	Rent	2022-06-17 14:32:37.502164+00	1
50	La Vie Boheme	Rent	2022-06-17 14:34:49.614495+00	1
51	Yorktown	Hamilton	2022-06-17 15:01:05.602285+00	1
61	We don't talk about  Bruno	Encanto	2022-06-21 05:09:50.014303+00	1
62	Brotherhood of Man	How to Succeed	2022-06-21 05:10:11.449852+00	1
63	You Won't Succeed on Broadway	Spamalot	2022-06-21 05:11:02.119231+00	1
64	Let's Do the Time Warp Again	The Rocky Horror Show	2022-07-05 15:15:48.358426+00	71
66	Hello	Book of Mormon	2022-07-21 08:46:47.415904+00	71
67	My Shot	Hamilton	2022-07-21 16:51:01.888515+00	115
68	Louder Than Words	Tick Tick Boom	2022-07-21 17:04:14.418118+00	125
69	Beauty and the Beast	Beauty and the Beast	2022-07-21 17:08:16.513488+00	116
70	Boho Days	Tick, Tick… Boom!	2022-07-21 17:09:40.325736+00	117
71	La Vi Boheme	Rent	2022-07-21 17:10:36.48385+00	127
\.


--
-- Data for Name: song_signup_singer; Type: TABLE DATA; Schema: public; Owner: twistdbadmin
--

COPY public.song_signup_singer (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, cy1_position, no_image_upload, cy2_position, cy3_position, lscy_position, placeholder) FROM stdin;
126	!Nn9jPdUYAMlUasZDyF4o2iIH8JO9x9NucjA8ZkyD	2022-07-21 16:43:36.011552+00	f	liah_biran	Liah	Biran		t	t	2022-07-21 16:43:35.994388+00	\N	f	\N	\N	\N	f
127	!t28ASMHgWKFhhbcRbE4XfrTLDqYIe5caFdDpV2Dl	2022-07-21 16:48:04.421244+00	f	shai_sadeh	Shai	Sadeh		t	t	2022-07-21 16:48:04.405679+00	\N	f	\N	\N	\N	f
128	!Rn2TQWl8Bk6hx9i0w2QiOzjAX8qfJNH1bymZJLCL	2022-07-21 16:48:29.105548+00	f	miya_hames	Miya	Hames		t	t	2022-07-21 16:48:29.089547+00	\N	f	\N	\N	\N	f
129	!08GrCkb2abo7rJnTgn3A7NI66wH5xKSwi3bz0TSN	2022-07-21 16:55:06.170939+00	f	rafi_serfaty	Rafi	Serfaty		t	t	2022-07-21 16:55:06.154868+00	\N	f	\N	\N	\N	f
130	!Xsii4PhmgjRUpRsxq2lbsukAa3FRO1BXnqxkoKm7	2022-07-21 16:56:07.14239+00	f	molly_cloutier	Molly	Cloutier		t	t	2022-07-21 16:56:07.135384+00	\N	f	\N	\N	\N	f
131	!lpoaAlwHb52GSR6YJIKCEhONTTyVnXHzuELGXcEo	2022-07-21 16:56:07.590856+00	f	avital_sykora	Avital	Sykora		t	t	2022-07-21 16:56:07.575377+00	\N	f	\N	\N	\N	f
132	!WCsNjnDDrkvKt39NlKVPOjZbGDp46zwQYbVZiPum	2022-07-21 17:14:50.375172+00	f	ariel_yehya	Ariel	Yehya		t	t	2022-07-21 17:14:50.358955+00	\N	f	\N	\N	\N	f
133	!vOQeEZJZwjeHV11AC4uTyrliQn0Nk7IJK1DTTeuA	2022-07-21 17:19:55.831069+00	f	dale_honor	Dale	Honor		t	t	2022-07-21 17:19:55.814561+00	\N	t	\N	\N	\N	f
134	!SGn8qOanuXANRqY9KTvjgvXKKsfQwuWtPFOj9Ya6	2022-07-21 17:35:05.238506+00	f	dalia_herszaft	Dalia	Herszaft		t	t	2022-07-21 17:35:05.221208+00	\N	t	\N	\N	\N	f
135	!vCNeW6vlKYlaNUew5ZJicNCA5eYukTUKuobBDtcT	2022-07-21 17:50:00.196+00	f	adina_weisblatt	Adina	Weisblatt		t	t	2022-07-21 17:50:00.162557+00	\N	f	\N	\N	\N	f
136	!tPEKGuOiPqmlwJzPL3EzLFzkANCZv6d8hXwP7dQN	2022-07-21 18:28:40.293852+00	f	dekel_farhi	Dekel	Farhi		t	t	2022-07-21 18:28:40.277655+00	\N	t	\N	\N	\N	f
137	!bO6zXY9yws7scdXaDOsOMBa39TwpkAob3MWkoIa1	2022-07-21 18:36:25.553781+00	f	yaacov_braul	Yaacov	Braul		t	t	2022-07-21 18:36:25.537875+00	\N	f	\N	\N	\N	f
138	!xBkMF19CoBEafFLiaPGQKY5Wvg0iw8g7OYzH2YZo	2022-07-21 18:48:41.485116+00	f	elisheva_b	Elisheva	B		t	t	2022-07-21 18:48:41.468871+00	\N	t	\N	\N	\N	f
139	!jWaDDy88Xbl8521Pf39R9Zcu1gBeyq4I3ubrKzOq	2022-07-21 19:03:41.117396+00	f	yoni_linder	Yoni	Linder		t	t	2022-07-21 19:03:41.100877+00	\N	f	\N	\N	\N	f
140	!ibZWpFpV3Im65775KBfYjRfdqyJczBkaV1w23isI	2022-07-21 19:03:44.097164+00	f	arielle_baum	Arielle	Baum		t	t	2022-07-21 19:03:44.072004+00	\N	f	\N	\N	\N	f
121	!exyB9zjWdWOqbyFApE94ZDhtAzyTcgnawSwYDQow	2022-07-21 19:31:17.244758+00	f	shelly_solomon	Shelly	Solomon		t	t	2022-07-21 16:29:28.7099+00	\N	f	\N	\N	\N	f
116	!NWPL2BpoEVAS1sXIaMqm12QcQa6inbL9DHPc9w67	2022-07-21 16:12:52.556962+00	f	elky_sigler	Elky	Sigler		t	t	2022-07-21 16:12:52.54806+00	\N	t	\N	\N	\N	f
1	pbkdf2_sha256$260000$MRi2Pgo7l2KOrhr2u8j516$jFtcJbTqnJWBg4z4APixtyE250F3DfcL4i8Refq/M+4=	2022-07-20 08:33:29.534885+00	t	alon_aviv	Alon	Aviv		t	t	2022-06-02 13:31:38+00	\N	f	\N	\N	\N	f
71	pbkdf2_sha256$260000$fH90rzL8iuGtoJd2RYwsZU$HHSiC6GEco6n4KY0R+trmtPU7SVVZDLuhzPyT7ixnwE=	2022-07-20 09:47:04.77927+00	t	shani_wahrman	Shani	Wahrman		t	t	2022-07-05 12:57:05+00	\N	f	\N	\N	\N	f
117	!FMMv2nzEiRYQoU4u8Vqi1KWPGdDNg85yx8tn5Chf	2022-07-21 16:13:44.428671+00	f	gadi_zaig	Gadi	Zaig		t	t	2022-07-21 16:13:44.412208+00	\N	f	\N	\N	\N	f
114	!oI9BAec40W0GkGz0lDuTNv7TUudbNJUpmfasV293	2022-07-21 16:08:33.555796+00	f	aliza_ben moha	Aliza	Ben Moha		t	t	2022-07-21 16:08:33.539792+00	\N	f	\N	\N	\N	f
115	!uRwsLGE203k7l7y4MR3AqLEWe05SDs5I8S9N9rrw	2022-07-21 16:11:48.31899+00	f	matan_rubin	Matan	Rubin		t	t	2022-07-21 16:11:48.303316+00	\N	f	\N	\N	\N	f
118	!hp2pXYmjvGvGUB9pIHi9mSkd025v5PxWoYhLeTge	2022-07-21 16:14:16.254967+00	f	michal_hass	Michal	Hass		t	t	2022-07-21 16:14:16.238996+00	\N	f	\N	\N	\N	f
119	!7nDVvgKFW0h0QWBRbtrstRpio3wN45G5kR9GWN2W	2022-07-21 16:22:42.28274+00	f	tamar_orbach	Tamar	Orbach		t	t	2022-07-21 16:22:42.266704+00	\N	f	\N	\N	\N	f
120	!qqTSJGlRpZ8YdXepzhOcjHrGKJzUfBcXhcG9cxEB	2022-07-21 16:26:54.905965+00	f	brian_hoffman	Brian	Hoffman		t	t	2022-07-21 16:26:54.890194+00	\N	f	\N	\N	\N	f
122	!tbJsd16ov8D1g0HKFzaWyAjAJXarNun5fyW43JZf	2022-07-21 16:39:10.724067+00	f	daniel_fox	Daniel	Fox		t	t	2022-07-21 16:39:10.708242+00	\N	f	\N	\N	\N	f
123	!zcTM0GRj7HBnVA4PVIdtxMuoQ5s6x8wwFKGIT9OH	2022-07-21 16:40:05.168193+00	f	candice_nemoff	Candice	Nemoff		t	t	2022-07-21 16:40:05.152176+00	\N	f	\N	\N	\N	f
124	!KUI69VMR5TUoVMsIA2f9QjLJhZI1j2EyOJtzHgzI	2022-07-21 16:42:54.142584+00	f	cb_davies	Cb	Davies		t	t	2022-07-21 16:42:54.12594+00	\N	f	\N	\N	\N	f
125	!35V0XRqnuEqzjRl9n4bXRPNCrCgZxer2yS61juAU	2022-07-21 16:42:59.073031+00	f	joey_geralnik	Joey	Geralnik		t	t	2022-07-21 16:42:59.057593+00	\N	f	\N	\N	\N	f
\.


--
-- Data for Name: song_signup_singer_groups; Type: TABLE DATA; Schema: public; Owner: twistdbadmin
--

COPY public.song_signup_singer_groups (id, singer_id, group_id) FROM stdin;
108	71	1
112	114	1
113	115	1
114	116	1
115	117	1
116	118	1
117	119	1
118	120	1
119	121	1
120	122	1
121	123	1
122	124	1
123	125	1
124	126	1
125	127	1
126	128	1
127	129	1
129	130	1
130	131	1
131	132	1
132	133	1
133	134	1
134	135	1
135	136	1
136	137	1
137	138	1
138	139	1
139	140	1
\.


--
-- Data for Name: song_signup_singer_user_permissions; Type: TABLE DATA; Schema: public; Owner: twistdbadmin
--

COPY public.song_signup_singer_user_permissions (id, singer_id, permission_id) FROM stdin;
\.


--
-- Data for Name: song_signup_songrequest; Type: TABLE DATA; Schema: public; Owner: twistdbadmin
--

COPY public.song_signup_songrequest (id, song_name, musical, request_time, performance_time, singer_id, priority, "position", duet_partner_id, cycle, placeholder) FROM stdin;
8316	Sincerely Me	Dear Evan Hansen	2022-07-21 18:49:13.237972+00	2022-07-21 19:22:58.213634+00	138	1	\N	135	\N	f
8308	Il'l Make a Man Out of You	Mulan	2022-07-21 18:30:09.45734+00	2022-07-21 19:17:44.001319+00	136	1	\N	132	\N	f
8298	She Used to Be Mine (If Possible, Lower Register)	Waitress	2022-07-21 17:55:36.342085+00	2022-07-21 19:12:40.233198+00	135	1	\N	\N	\N	f
8310	Take Me or Leave Ma	Rent	2022-07-21 18:35:53.16617+00	2022-07-21 19:03:39.774824+00	118	3	\N	\N	\N	f
8288	Waving Through a Window	Dear Evan Hansen	2022-07-21 17:22:57.149455+00	2022-07-21 18:46:18.823285+00	133	1	\N	\N	\N	f
8312	Marry the Man Today	Guys & Dolls	2022-07-21 18:37:43.332078+00	\N	131	3	\N	122	\N	f
8281	A Whole New World	Aladdin	2022-07-21 17:10:17.949588+00	2022-07-21 18:36:22.532192+00	116	3	\N	\N	\N	f
8309	Breathe	In the Heights	2022-07-21 18:32:03.501301+00	\N	126	7	\N	\N	\N	f
8272	The Story of Lucy and Jessie	Follies	2022-07-21 16:56:43.467636+00	2022-07-21 18:30:33.72045+00	131	1	\N	\N	\N	f
8266	If You Hadn't, but You Did	Two on the Aisle	2022-07-21 16:41:22.382342+00	2022-07-21 18:09:17.206863+00	122	1	\N	\N	\N	f
8285	If I Were a Rich Man	Fiddler	2022-07-21 17:18:23.531322+00	2022-07-21 18:02:45.548423+00	120	2	\N	\N	\N	f
8278	Is This Home	Beauty and the Beast	2022-07-21 17:00:13.375647+00	2022-07-21 17:57:16.557248+00	128	1	\N	\N	\N	f
8315	Candy Store	Heathers	2022-07-21 18:46:28.024471+00	\N	126	8	\N	118	\N	f
8307	Road to Hell	Hadestown	2022-07-21 18:26:29.580935+00	\N	132	1	10	115	\N	f
8314	Meant to Be Yours	Heathers	2022-07-21 18:45:13.653294+00	\N	119	5	11	\N	\N	f
8313	As Long as You're Mine	Wicked	2022-07-21 18:44:52.587174+00	2022-07-21 19:50:48.090728+00	115	1	\N	118	\N	f
8317	Rent	Rent	2022-07-21 18:55:03.452541+00	2022-07-21 19:47:12.259658+00	127	2	\N	132	\N	f
8303	Boho Days	Tick, Tick… Boom!	2022-07-21 18:20:27.966513+00	2022-07-21 19:41:25.465288+00	117	2	\N	\N	\N	f
8319	What Baking Can Do	Waitress	2022-07-21 18:59:20.756727+00	2022-07-21 19:37:10.470481+00	121	2	\N	\N	\N	f
8289	Satisfied	Hamilton	2022-07-21 17:28:47.339074+00	2022-07-21 19:32:32.24028+00	126	2	\N	\N	\N	f
8279	We Both Reached for the Gun	Chicago	2022-07-21 17:05:09.172142+00	2022-07-21 17:51:37.320873+00	127	1	\N	115	\N	f
8295	Bring Him Home	Les Miserables	2022-07-21 17:46:28.82776+00	\N	133	3	\N	\N	\N	f
8286	Prologue	Natasha, Pierre and the Great Comet of 1812	2022-07-21 17:19:21.94543+00	\N	129	5	\N	\N	\N	f
8280	How I Know You	Aida	2022-07-21 17:07:00.491791+00	\N	129	3	\N	71	\N	f
8264	Putting It Together	Barbra Streisand	2022-07-21 16:36:14.625768+00	2022-07-21 17:01:57.386246+00	116	2	\N	\N	\N	f
8268	Feed Me	Little Shop	2022-07-21 16:48:08.227303+00	2022-07-21 16:55:04.340942+00	120	1	\N	122	\N	f
8287	Not Alone	A Very Potter Musical	2022-07-21 17:22:33.767988+00	2022-07-21 19:26:50.308876+00	124	2	\N	128	\N	f
8296	Take Me or Leave Me	Rent	2022-07-21 17:48:26.948109+00	\N	134	2	7	118	\N	f
8294	All That Jazz	Chicago	2022-07-21 17:45:33.816118+00	\N	126	3	9	\N	\N	f
8292	I Didn’t Plan It	Waitress	2022-07-21 17:35:26.393344+00	2022-07-21 19:08:44.765874+00	134	1	\N	\N	\N	f
8257	Putting It Together	Barbra	2022-07-21 16:13:03.189543+00	2022-07-21 16:35:53.114303+00	116	1	\N	\N	\N	f
8290	Just One Step	Songs for a New World	2022-07-21 17:29:55.86357+00	2022-07-21 19:51:57.683182+00	119	4	\N	\N	\N	f
8256	זה לא בשבילי	שלמה המלך ושלמי הסנדלר	2022-07-21 16:09:33.928457+00	2022-07-21 16:31:17.185867+00	114	1	\N	\N	\N	f
8261	בלי םפאניקה אניקה	בילי שוורץ	2022-07-21 16:28:51.582533+00	2022-07-21 17:16:19.342723+00	119	2	\N	\N	\N	f
8275	Boundaries	A Strange Loop	2022-07-21 16:58:03.47511+00	\N	131	2	\N	\N	\N	f
8282	Settle for Me	Crazy Ex Girlfriend	2022-07-21 17:10:49.451959+00	\N	129	4	\N	\N	\N	f
8269	I Can Hear the Bells	Hairspray	2022-07-21 16:50:43.29619+00	2022-07-21 17:22:45.068822+00	125	1	\N	\N	\N	f
8274	Words Fail	Dear Evan Hansen	2022-07-21 16:57:37.618526+00	2022-07-21 18:18:54.030409+00	129	1	\N	\N	\N	f
8299	Never Enough	The Greatest Showman	2022-07-21 17:57:21.723552+00	\N	126	5	\N	\N	\N	f
8265	30/90	Tick, Tick… Boom!	2022-07-21 16:36:19.735672+00	2022-07-21 16:47:52.345214+00	117	1	\N	\N	\N	f
8263	I Know Things Now	Into the Woods	2022-07-21 16:33:04.381956+00	2022-07-21 16:40:06.061391+00	118	1	\N	\N	\N	f
8297	On My Own	Les Misérables	2022-07-21 17:52:09.166656+00	\N	126	4	\N	\N	\N	f
8258	Everything's Alright	Jesus Christ	2022-07-21 16:14:59.256114+00	2022-07-21 16:55:04.413763+00	114	2	\N	1	\N	f
8300	Home	Beauty and the Beast	2022-07-21 17:57:53.103+00	\N	126	6	\N	\N	\N	f
8305	Be Prepared	Lion King	2022-07-21 18:23:26.592578+00	\N	120	3	1	1	\N	f
8306	My New Philosophy	You're a Good Man, Charlie Brown	2022-07-21 18:25:05.92366+00	\N	122	2	2	131	\N	f
8277	You're Welcome	Moana	2022-07-21 16:59:22.897208+00	\N	129	2	3	\N	\N	f
8273	No Good Deed	Wicked	2022-07-21 16:57:31.099375+00	\N	130	2	4	\N	\N	f
8293	Wait for It	Hamilton	2022-07-21 17:38:10.588599+00	\N	133	2	5	\N	\N	f
8318	Enough 2	In the Heights	2022-07-21 18:55:38.03164+00	\N	125	3	6	\N	\N	f
8301	Dancing Through Life	Wicked	2022-07-21 18:04:59.378117+00	\N	124	3	8	\N	\N	f
8283	Enough	In the Heights	2022-07-21 17:13:54.107678+00	2022-07-21 18:52:47.655625+00	125	2	\N	71	\N	f
8262	Right Hand Man	Something Rotten	2022-07-21 16:29:23.8661+00	2022-07-21 18:41:15.03841+00	119	3	\N	1	\N	f
8271	In My Own Little Corner	Cinderella	2022-07-21 16:56:22.209031+00	2022-07-21 18:35:42.666292+00	130	1	\N	\N	\N	f
8291	You're Welcome	Heathers	2022-07-21 17:34:14.581361+00	2022-07-21 17:47:01.730272+00	121	1	\N	117	\N	f
8267	Watch What Happens	Newsies	2022-07-21 16:45:38.110877+00	2022-07-21 17:37:08.842528+00	126	1	\N	\N	\N	f
8284	Bring Him Home English/Hebrew	Les Miserables	2022-07-21 17:15:37.884026+00	2022-07-21 17:31:28.513101+00	124	1	\N	132	\N	f
8276	Summer in Ohio	The Last Five Years	2022-07-21 16:59:15.689618+00	2022-07-21 17:25:27.873762+00	118	2	\N	\N	\N	f
8259	Welcome to Nowhere	The Band's Visit	2022-07-21 16:23:28.903512+00	2022-07-21 16:39:10.952802+00	119	1	\N	\N	\N	f
\.


--
-- Data for Name: song_signup_songrequest_additional_singers; Type: TABLE DATA; Schema: public; Owner: twistdbadmin
--

COPY public.song_signup_songrequest_additional_singers (id, songrequest_id, singer_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: twistdbadmin
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: twistdbadmin
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 2, true);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: twistdbadmin
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 36, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: twistdbadmin
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 77, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: twistdbadmin
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 9, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: twistdbadmin
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 46, true);


--
-- Name: flags_flagstate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: twistdbadmin
--

SELECT pg_catalog.setval('public.flags_flagstate_id_seq', 1, true);


--
-- Name: song_signup_groupsongrequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: twistdbadmin
--

SELECT pg_catalog.setval('public.song_signup_groupsongrequest_id_seq', 71, true);


--
-- Name: song_signup_singer_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: twistdbadmin
--

SELECT pg_catalog.setval('public.song_signup_singer_groups_id_seq', 140, true);


--
-- Name: song_signup_singer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: twistdbadmin
--

SELECT pg_catalog.setval('public.song_signup_singer_id_seq', 140, true);


--
-- Name: song_signup_singer_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: twistdbadmin
--

SELECT pg_catalog.setval('public.song_signup_singer_user_permissions_id_seq', 1, false);


--
-- Name: song_signup_songrequest_additional_singers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: twistdbadmin
--

SELECT pg_catalog.setval('public.song_signup_songrequest_additional_singers_id_seq', 1, false);


--
-- Name: song_signup_songrequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: twistdbadmin
--

SELECT pg_catalog.setval('public.song_signup_songrequest_id_seq', 8319, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: flags_flagstate flags_flagstate_name_condition_value_4e81ec48_uniq; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.flags_flagstate
    ADD CONSTRAINT flags_flagstate_name_condition_value_4e81ec48_uniq UNIQUE (name, condition, value);


--
-- Name: flags_flagstate flags_flagstate_pkey; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.flags_flagstate
    ADD CONSTRAINT flags_flagstate_pkey PRIMARY KEY (id);


--
-- Name: song_signup_groupsongrequest song_signup_groupsongrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_groupsongrequest
    ADD CONSTRAINT song_signup_groupsongrequest_pkey PRIMARY KEY (id);


--
-- Name: song_signup_singer_groups song_signup_singer_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_singer_groups
    ADD CONSTRAINT song_signup_singer_groups_pkey PRIMARY KEY (id);


--
-- Name: song_signup_singer_groups song_signup_singer_groups_singer_id_group_id_0c2bce52_uniq; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_singer_groups
    ADD CONSTRAINT song_signup_singer_groups_singer_id_group_id_0c2bce52_uniq UNIQUE (singer_id, group_id);


--
-- Name: song_signup_singer song_signup_singer_pkey; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_singer
    ADD CONSTRAINT song_signup_singer_pkey PRIMARY KEY (id);


--
-- Name: song_signup_singer_user_permissions song_signup_singer_user__singer_id_permission_id_d96a7da1_uniq; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_singer_user_permissions
    ADD CONSTRAINT song_signup_singer_user__singer_id_permission_id_d96a7da1_uniq UNIQUE (singer_id, permission_id);


--
-- Name: song_signup_singer_user_permissions song_signup_singer_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_singer_user_permissions
    ADD CONSTRAINT song_signup_singer_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: song_signup_singer song_signup_singer_username_key; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_singer
    ADD CONSTRAINT song_signup_singer_username_key UNIQUE (username);


--
-- Name: song_signup_songrequest_additional_singers song_signup_songrequest__songrequest_id_singer_id_1b295821_uniq; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_songrequest_additional_singers
    ADD CONSTRAINT song_signup_songrequest__songrequest_id_singer_id_1b295821_uniq UNIQUE (songrequest_id, singer_id);


--
-- Name: song_signup_songrequest_additional_singers song_signup_songrequest_additional_singers_pkey; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_songrequest_additional_singers
    ADD CONSTRAINT song_signup_songrequest_additional_singers_pkey PRIMARY KEY (id);


--
-- Name: song_signup_songrequest song_signup_songrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_songrequest
    ADD CONSTRAINT song_signup_songrequest_pkey PRIMARY KEY (id);


--
-- Name: song_signup_songrequest song_signup_songrequest_song_name_musical_singer_d2c870a5_uniq; Type: CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_songrequest
    ADD CONSTRAINT song_signup_songrequest_song_name_musical_singer_d2c870a5_uniq UNIQUE (song_name, musical, singer_id, cycle, "position");


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: song_signup_groupsongrequest_requested_by_id_28ee6931; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX song_signup_groupsongrequest_requested_by_id_28ee6931 ON public.song_signup_groupsongrequest USING btree (requested_by_id);


--
-- Name: song_signup_singer_groups_group_id_dd867d90; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX song_signup_singer_groups_group_id_dd867d90 ON public.song_signup_singer_groups USING btree (group_id);


--
-- Name: song_signup_singer_groups_singer_id_2c98845b; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX song_signup_singer_groups_singer_id_2c98845b ON public.song_signup_singer_groups USING btree (singer_id);


--
-- Name: song_signup_singer_user_permissions_permission_id_94d0d848; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX song_signup_singer_user_permissions_permission_id_94d0d848 ON public.song_signup_singer_user_permissions USING btree (permission_id);


--
-- Name: song_signup_singer_user_permissions_singer_id_20ebc8cd; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX song_signup_singer_user_permissions_singer_id_20ebc8cd ON public.song_signup_singer_user_permissions USING btree (singer_id);


--
-- Name: song_signup_singer_username_b362f1d1_like; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX song_signup_singer_username_b362f1d1_like ON public.song_signup_singer USING btree (username varchar_pattern_ops);


--
-- Name: song_signup_songrequest_ad_songrequest_id_2e38e58b; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX song_signup_songrequest_ad_songrequest_id_2e38e58b ON public.song_signup_songrequest_additional_singers USING btree (songrequest_id);


--
-- Name: song_signup_songrequest_additional_singers_singer_id_a529a8f4; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX song_signup_songrequest_additional_singers_singer_id_a529a8f4 ON public.song_signup_songrequest_additional_singers USING btree (singer_id);


--
-- Name: song_signup_songrequest_duet_partner_id_5dad5c17; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX song_signup_songrequest_duet_partner_id_5dad5c17 ON public.song_signup_songrequest USING btree (duet_partner_id);


--
-- Name: song_signup_songrequest_singer_id_d2a4ad82; Type: INDEX; Schema: public; Owner: twistdbadmin
--

CREATE INDEX song_signup_songrequest_singer_id_d2a4ad82 ON public.song_signup_songrequest USING btree (singer_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_song_signup_singer_id; Type: FK CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_song_signup_singer_id FOREIGN KEY (user_id) REFERENCES public.song_signup_singer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: song_signup_groupsongrequest song_signup_groupson_requested_by_id_28ee6931_fk_song_sign; Type: FK CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_groupsongrequest
    ADD CONSTRAINT song_signup_groupson_requested_by_id_28ee6931_fk_song_sign FOREIGN KEY (requested_by_id) REFERENCES public.song_signup_singer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: song_signup_singer_groups song_signup_singer_g_singer_id_2c98845b_fk_song_sign; Type: FK CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_singer_groups
    ADD CONSTRAINT song_signup_singer_g_singer_id_2c98845b_fk_song_sign FOREIGN KEY (singer_id) REFERENCES public.song_signup_singer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: song_signup_singer_groups song_signup_singer_groups_group_id_dd867d90_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_singer_groups
    ADD CONSTRAINT song_signup_singer_groups_group_id_dd867d90_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: song_signup_singer_user_permissions song_signup_singer_u_permission_id_94d0d848_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_singer_user_permissions
    ADD CONSTRAINT song_signup_singer_u_permission_id_94d0d848_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: song_signup_singer_user_permissions song_signup_singer_u_singer_id_20ebc8cd_fk_song_sign; Type: FK CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_singer_user_permissions
    ADD CONSTRAINT song_signup_singer_u_singer_id_20ebc8cd_fk_song_sign FOREIGN KEY (singer_id) REFERENCES public.song_signup_singer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: song_signup_songrequest song_signup_songrequ_duet_partner_id_5dad5c17_fk_song_sign; Type: FK CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_songrequest
    ADD CONSTRAINT song_signup_songrequ_duet_partner_id_5dad5c17_fk_song_sign FOREIGN KEY (duet_partner_id) REFERENCES public.song_signup_singer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: song_signup_songrequest_additional_singers song_signup_songrequ_singer_id_a529a8f4_fk_song_sign; Type: FK CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_songrequest_additional_singers
    ADD CONSTRAINT song_signup_songrequ_singer_id_a529a8f4_fk_song_sign FOREIGN KEY (singer_id) REFERENCES public.song_signup_singer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: song_signup_songrequest song_signup_songrequ_singer_id_d2a4ad82_fk_song_sign; Type: FK CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_songrequest
    ADD CONSTRAINT song_signup_songrequ_singer_id_d2a4ad82_fk_song_sign FOREIGN KEY (singer_id) REFERENCES public.song_signup_singer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: song_signup_songrequest_additional_singers song_signup_songrequ_songrequest_id_2e38e58b_fk_song_sign; Type: FK CONSTRAINT; Schema: public; Owner: twistdbadmin
--

ALTER TABLE ONLY public.song_signup_songrequest_additional_singers
    ADD CONSTRAINT song_signup_songrequ_songrequest_id_2e38e58b_fk_song_sign FOREIGN KEY (songrequest_id) REFERENCES public.song_signup_songrequest(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

