# Generated by Django 3.1.2 on 2025-11-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('musical', models.CharField(max_length=255)),
                ('event_sku', models.CharField(max_length=128)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('chosen', models.BooleanField(default=False)),
                ('chosen_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-votes', '-created_at'),
            },
        ),
    ]
