FROM python:3.10

ENV PYTHONUNBUFFERED=1

WORKDIR /twist/

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN apt-get update && apt-get install -y postgresql-client # In order to use pg_dump

EXPOSE 8000
