# Generated by Django 3.1.2 on 2021-09-13 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50)),
                ('musical', models.CharField(max_length=50)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('performance_time', models.DateTimeField(default=None, null=True)),
                ('priority', models.IntegerField()),
                ('additional_singers', models.ManyToManyField(blank=True, related_name='songs', to=settings.AUTH_USER_MODEL)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('song_name', 'musical', 'singer')},
            },
        ),
    ]
