# Generated by Django 3.1.2 on 2021-09-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='SongRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50)),
                ('musical', models.CharField(max_length=50)),
                ('request_time', models.TimeField(auto_now_add=True)),
                ('performance_time', models.TimeField(default=None)),
                ('singers', models.ManyToManyField(related_name='song_requests', to='song_signup.Singer')),
            ],
        ),
    ]
