# Generated by Django 3.1.2 on 2021-09-13 19:49

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0001_initial'),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name='songrequest',
            name='musical',
            field=django.contrib.postgres.fields.citext.CITextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='song_name',
            field=django.contrib.postgres.fields.citext.CITextField(max_length=50),
        ),
    ]
