# Generated by Django 3.1.2 on 2021-09-11 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('song_signup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Singer',
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='performance_time',
            field=models.TimeField(default=None, null=True),
        ),
        # migrations.AlterField(
        #     model_name='songrequest',
        #     name='singers',
        #     field=models.ManyToManyField(related_name='song_requests', to=settings.AUTH_USER_MODEL),
        # ),
    ]
