# Generated by Django 3.2.13 on 2022-05-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singer',
            options={'verbose_name': 'Singer', 'verbose_name_plural': 'Singers'},
        ),
        migrations.RenameField(
            model_name='singer',
            old_name='position',
            new_name='cycle1_position',
        ),
        migrations.AddField(
            model_name='singer',
            name='cycle2_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singer',
            name='cycle3_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
