# Generated by Django 3.1.2 on 2021-09-11 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('song_signup', '0002_auto_20210911_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songrequest',
            name='singers',
        ),
        migrations.AddField(
            model_name='songrequest',
            name='singer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
