# Generated by Django 3.1.2 on 2021-09-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0002_auto_20210913_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrequest',
            name='priority',
            field=models.IntegerField(verbose_name='Queue Order'),
        ),
    ]
