# Generated by Django 3.2.13 on 2022-06-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0003_auto_20220531_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
