# Generated by Django 3.1.2 on 2021-09-11 16:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('song_signup', '0003_auto_20210911_1549'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='songrequest',
            unique_together={('song_name', 'musical', 'singer')},
        ),
    ]
