# Generated by Django 3.2.13 on 2022-06-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0004_songrequest_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
