# Generated by Django 3.1.2 on 2021-09-12 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('song_signup', '0004_auto_20210911_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='additional_singers',
            field=models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
