# Generated by Django 3.2.13 on 2022-06-01 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0005_songrequest_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songrequest',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='songrequest',
            name='duet_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duet_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
