# Generated by Django 3.1.2 on 2022-05-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0005_auto_20211019_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrequest',
            name='performance_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='priority',
            field=models.IntegerField(blank=True, default=0, verbose_name='Queue Order'),
        ),
    ]
