# Generated by Django 3.2.13 on 2022-06-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0006_auto_20220601_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='cycle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
