# Generated by Django 3.1.2 on 2021-09-12 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('song_signup', '0006_auto_20210912_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrequest',
            name='additional_singers',
            field=models.ManyToManyField(blank=True, related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
