# Generated by Django 3.1.2 on 2021-09-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0007_auto_20210912_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
