# Generated by Django 3.2.13 on 2022-05-24 22:55

from django.conf import settings
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('song_signup', '0007_auto_20220520_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSongRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', django.contrib.postgres.fields.citext.CITextField(max_length=50)),
                ('musical', django.contrib.postgres.fields.citext.CITextField(max_length=50)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
