# Generated by Django 3.1.2 on 2022-07-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0009_auto_20220602_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='lscy_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
