# Generated by Django 3.1.2 on 2021-09-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0009_auto_20210912_2040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Singer',
        ),
    ]
