# Generated by Django 3.1.2 on 2022-07-03 20:39

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0010_singer_lscy_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrequest',
            name='cycle',
            field=django.contrib.postgres.fields.citext.CITextField(blank=True, null=True),
        ),
    ]
