# Generated by Django 3.1.2 on 2021-09-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0011_singer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Singer',
        ),
    ]
