# Generated by Django 3.1.2 on 2022-07-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0012_auto_20220704_1655'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='songrequest',
            unique_together={('song_name', 'musical', 'singer', 'cycle', 'position')},
        ),
    ]
