# Generated by Django 3.1.2 on 2022-07-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0013_auto_20220704_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
