# Generated by Django 3.1.2 on 2022-07-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0014_songrequest_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
