# Generated by Django 3.1.2 on 2022-08-27 19:30

from django.conf import settings
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0017_songrequest_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='notes',
            field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=1000, null=True),
        ),
    ]
