# Generated by Django 3.1.2 on 2022-08-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0018_auto_20220827_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupsongrequest',
            old_name='requested_by',
            new_name='suggested_by',
        ),
    ]
