# Generated by Django 3.1.2 on 2022-08-28 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0019_auto_20220827_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrequest',
            name='singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
