# Generated by Django 3.1.2 on 2022-08-28 16:07

from django.conf import settings
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0020_auto_20220828_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songrequest',
            name='suggested_by',
        ),
        migrations.CreateModel(
            name='SongSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', django.contrib.postgres.fields.citext.CITextField(max_length=50)),
                ('musical', django.contrib.postgres.fields.citext.CITextField(max_length=50)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs_suggested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
