# Generated by Django 3.1.2 on 2023-10-02 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0022_songrequest_suggested_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongLyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.TextField()),
                ('artist_name', models.TextField()),
                ('lyrics', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
                ('group_song_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='song_signup.groupsongrequest')),
                ('song_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='song_signup.songrequest')),
            ],
            options={
                'verbose_name_plural': 'Song lyrics',
            },
        ),
    ]
