# Generated by Django 3.1.2 on 2024-01-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0023_songlyrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('event_sku', models.CharField(max_length=20)),
                ('event_name', models.CharField(max_length=100)),
                ('num_tickets', models.IntegerField()),
                ('ticket_type', models.CharField(choices=[('SING', 'Singer Ticket'), ('ATTN', 'Audience Ticket')], max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('order_id', 'event_sku', 'ticket_type')},
            },
        ),
    ]
