# Generated by Django 3.1.2 on 2024-01-24 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0024_ticketorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='ticket_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='singers', to='song_signup.ticketorder'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='ticket_type',
            field=models.CharField(choices=[('SING', 'Singer'), ('ATTN', 'Audience')], max_length=20),
        ),
    ]
