# Generated by Django 3.1.2 on 2024-02-05 21:01

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0025_auto_20240124_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsongrequest',
            name='suggested_by',
            field=django.contrib.postgres.fields.citext.CITextField(default='-', max_length=50, null=True),
        ),
    ]
