# Generated by Django 3.1.2 on 2024-02-19 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0026_auto_20240205_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsongrequest',
            name='performance_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='CurrentGroupSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_song', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='song_signup.groupsongrequest')),
            ],
        ),
    ]
