# Generated by Django 3.1.2 on 2024-02-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0027_auto_20240219_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='is_freebee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='event_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
