# Generated by Django 3.1.2 on 2024-02-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0028_auto_20240226_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
