# Generated by Django 3.1.2 on 2024-03-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0030_auto_20240325_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songrequest',
            name='suggested_by',
        ),
    ]
