# Generated by Django 3.1.2 on 2024-04-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0031_remove_songrequest_suggested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentgroupsong',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
