# Generated by Django 3.1.2 on 2024-04-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0032_currentgroupsong_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='has_default_lyrics',
            field=models.BooleanField(default=False),
        ),
    ]
