# Generated by Django 3.1.2 on 2024-04-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0033_songrequest_has_default_lyrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songrequest',
            old_name='has_default_lyrics',
            new_name='default_lyrics',
        ),
        migrations.AddField(
            model_name='songrequest',
            name='found_music',
            field=models.BooleanField(default=False),
        ),
    ]
