# Generated by Django 3.1.2 on 2024-04-12 10:21

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0036_auto_20240408_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsongrequest',
            name='type',
            field=django.contrib.postgres.fields.citext.CITextField(choices=[('USER', 'USER'), ('REGULAR', 'REGULAR'), ('DRINKING-SONG', 'DRINKING-SONG'), ('OPENING', 'OPENING'), ('CLOSING', 'CLOSING')], default='USER', max_length=20),
        ),
    ]
