# Generated by Django 3.1.2 on 2024-09-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0038_auto_20240517_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='cy1_position',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='cy2_position',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='cy3_position',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='lscy_position',
        ),
        migrations.AlterUniqueTogether(
            name='songrequest',
            unique_together={('song_name', 'musical', 'singer', 'position')},
        ),
        migrations.RemoveField(
            model_name='songrequest',
            name='cycle',
        ),
    ]
