# Generated by Django 3.1.2 on 2024-05-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0038_auto_20240517_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='songlyrics',
            name='has_drinking_words',
            field=models.BooleanField(default=False),
        ),
    ]
