# Generated by Django 3.1.2 on 2024-06-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0038_auto_20240517_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrequest',
            name='position',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
