# Generated by Django 3.1.2 on 2024-09-22 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0039_auto_20240921_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songrequest',
            name='additional_singers',
        ),
        migrations.RemoveField(
            model_name='songrequest',
            name='duet_partner',
        ),
        migrations.AddField(
            model_name='songrequest',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='songs_as_partner', to=settings.AUTH_USER_MODEL),
        ),
    ]
