# Generated by Django 3.1.2 on 2024-09-26 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0040_auto_20240922_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choiceA', models.TextField()),
                ('choiceB', models.TextField()),
                ('choiceC', models.TextField()),
                ('choiceD', models.TextField()),
                ('answer', models.IntegerField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])),
            ],
        ),
        migrations.CreateModel(
            name='TriviaResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song_signup.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
