# Generated by Django 3.1.2 on 2024-09-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0041_question_triviaresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')]),
        ),
        migrations.AlterField(
            model_name='triviaresponse',
            name='choice',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')]),
        ),
    ]
