# Generated by Django 3.1.2 on 2024-10-02 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0042_auto_20240926_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choiceA', models.TextField()),
                ('choiceB', models.TextField()),
                ('choiceC', models.TextField()),
                ('choiceD', models.TextField()),
                ('answer', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')])),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='triviaresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='triviaresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='song_signup.triviaquestion'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
