# Generated by Django 3.1.2 on 2024-10-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0043_auto_20241002_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='is_audience',
            field=models.BooleanField(default=False),
        ),
    ]
