# Generated by Django 3.1.2 on 2024-10-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0047_auto_20241007_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaquestion',
            name='question',
            field=models.TextField(max_length=72),
        ),
    ]
