# Generated by Django 3.1.2 on 2024-10-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0048_auto_20241008_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquestion',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
