# Generated by Django 3.1.2 on 2024-11-01 13:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0049_triviaquestion_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='logged_in_customers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
