# Generated by Django 3.1.2 on 2024-11-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0050_ticketorder_logged_in_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='logged_in_customers',
            field=models.JSONField(default=list),
        ),
    ]
