# Generated by Django 3.1.2 on 2024-11-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0051_auto_20241101_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='logged_in_customers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
