# Generated by Django 3.1.2 on 2024-11-08 20:57

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0052_auto_20241101_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='to_alon',
            field=django.contrib.postgres.fields.citext.CITextField(blank=True, max_length=1000, null=True),
        ),
    ]
