# Generated by Django 3.1.2 on 2024-11-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0053_songrequest_to_alon'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/'),
        ),
    ]
