# Generated by Django 3.1.2 on 2024-11-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0054_singer_selfie'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
