# Generated by Django 3.1.2 on 2025-04-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0055_ticketorder_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('event_date', models.CharField(max_length=100, null=True)),
                ('event_sku', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('celebrating', models.TextField()),
            ],
        ),
    ]
