# Generated by Django 3.1.2 on 2025-02-21 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0055_ticketorder_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledGroupSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('group_song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='song_signup.groupsongrequest')),
            ],
        ),
    ]
