# Generated by Django 3.1.2 on 2025-05-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0056_celebration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='lead',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
