# Generated by Django 3.1.2 on 2025-05-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0056_celebration'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='spotlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
