# Generated by Django 3.1.2 on 2025-02-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0056_scheduledgroupsong'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledgroupsong',
            options={'ordering': ['position']},
        ),
    ]
