# Generated by Django 3.1.2 on 2025-05-11 20:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0057_auto_20250510_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('in_wa_group', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_orders', to='song_signup.customer'),
        ),
    ]
