# Generated by Django 3.1.2 on 2025-05-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0057_auto_20250526_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='standby',
            field=models.BooleanField(default=False),
        ),
    ]
