# Generated by Django 3.1.2 on 2025-02-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0058_auto_20250221_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledgroupsong',
            name='position',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
