# Generated by Django 3.1.2 on 2025-02-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0059_auto_20250221_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledgroupsong',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
