# Generated by Django 3.1.2 on 2025-05-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0059_songrequest_raffle_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songrequest',
            name='raffle_winner',
        ),
        migrations.AddField(
            model_name='singer',
            name='raffle_winner',
            field=models.BooleanField(default=False),
        ),
    ]
