# Generated by Django 3.1.2 on 2025-02-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0060_auto_20250221_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledgroupsong',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
