# Generated by Django 3.1.2 on 2025-07-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0061_auto_20250624_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquestion',
            name='choices_font_size',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='triviaquestion',
            name='question_font_size',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='question',
            field=models.TextField(),
        ),
    ]
