# Generated by Django 3.1.2 on 2025-02-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0061_auto_20250221_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledgroupsong',
            options={'ordering': ['song_pos']},
        ),
        migrations.RenameField(
            model_name='scheduledgroupsong',
            old_name='position',
            new_name='song_pos',
        ),
    ]
