# Generated by Django 3.1.2 on 2025-11-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0063_auto_20250712_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='is_peoples_choice',
            field=models.BooleanField(default=False),
        ),
    ]
