# Generated by Django 5.1.6 on 2025-02-21 17:20

from django.db import migrations
from django.contrib.postgres.operations import CreateCollation


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0063_alter_groupsongrequest_musical_and_more'),
    ]

    operations = [
        CreateCollation(
            "case_insensitive",
            provider="icu",
            locale="und-u-ks-level2",  # Language-agnostic Unicode collation
            deterministic=False
        ),
    ]
