# Generated by Django 3.1.2 on 2025-07-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0063_auto_20250712_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentLyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.TextField()),
                ('artist_name', models.TextField()),
                ('lyrics', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Persistent lyrics',
            },
        ),
    ]
