# Generated by Django 3.1.2 on 2025-07-26 19:17

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0064_auto_20250726_1917'),
    ]

    operations = [
        TrigramExtension(),
    ]
