# Generated by Django 5.1.6 on 2025-02-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0064_create_case_insensitive_collation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsongrequest',
            name='musical',
            field=models.TextField(db_collation='case_insensitive', max_length=50),
        ),
        migrations.AlterField(
            model_name='groupsongrequest',
            name='suggested_by',
            field=models.TextField(db_collation='case_insensitive', default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='groupsongrequest',
            name='type',
            field=models.TextField(choices=[('USER', 'USER'), ('REGULAR', 'REGULAR'), ('DRINKING-SONG', 'DRINKING-SONG'), ('OPENING', 'OPENING'), ('CLOSING', 'CLOSING')], db_collation='case_insensitive', default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='musical',
            field=models.TextField(db_collation='case_insensitive', max_length=50),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='notes',
            field=models.TextField(blank=True, db_collation='case_insensitive', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='song_name',
            field=models.TextField(db_collation='case_insensitive', max_length=50),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='to_alon',
            field=models.TextField(blank=True, db_collation='case_insensitive', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='songsuggestion',
            name='musical',
            field=models.TextField(db_collation='case_insensitive', max_length=50),
        ),
        migrations.AlterField(
            model_name='songsuggestion',
            name='song_name',
            field=models.TextField(db_collation='case_insensitive', max_length=50),
        ),
    ]
