# Generated by Django 3.1.2 on 2026-09-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0064_songrequest_is_peoples_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmingOptOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('is_audience', models.BooleanField(default=False)),
                ('event_date', models.CharField(blank=True, default='', max_length=100)),
                ('event_sku', models.CharField(blank=True, default='', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='selfies/')),
                ('songs_performed', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Filming opt-out',
                'verbose_name_plural': 'Filming opt-outs',
                'ordering': ('-recorded_at', 'full_name'),
            },
        ),
    ]
