# Generated by Django 3.1.2 on 2025-10-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0064_songrequest_crowd_pleaser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='songsuggestion',
            unique_together={('song_name', 'musical')},
        ),
    ]
