# Generated by Django 5.1.6 on 2025-02-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0065_alter_groupsongrequest_musical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsongrequest',
            name='song_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduledgroupsong',
            name='song_pos',
            field=models.PositiveIntegerField(),
        ),
    ]
