# Generated by Django 3.1.2 on 2025-10-29 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0065_auto_20251028_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='songsuggestion',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='songsuggestion',
            name='suggested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested', to=settings.AUTH_USER_MODEL),
        ),
    ]
