# Generated by Django 3.1.2 on 2026-09-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0065_filmingoptout'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmingoptout',
            name='songs_performed',
            field=models.TextField(blank=True, default=''),
        ),
    ]
