# Generated by Django 3.1.2 on 2025-10-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0066_auto_20251029_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='songsuggestion',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
