# Generated by Django 5.1.6 on 2025-02-22 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0066_alter_groupsongrequest_song_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledgroupsong',
            name='song_pos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song_suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song_signup.groupsongrequest')),
            ],
            options={
                'unique_together': {('singer', 'song_suggestion')},
            },
        ),
    ]
