# Generated by Django 5.1.6 on 2025-02-22 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_signup', '0067_alter_scheduledgroupsong_song_pos_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vote',
            name='singer',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='song_suggestion',
        ),
        migrations.AddField(
            model_name='groupsongrequest',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SongSuggestion',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
