# Generated by Django 3.1.2 on 2026-02-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(choices=[(1, 'Round 1'), (2, 'Round 2'), (3, 'Round 3'), (4, 'Round 4'), (5, 'Round 5'), (6, 'Round 6')], help_text='Round 1 through 6.', unique=True)),
                ('url', models.URLField(blank=True, help_text='Link for this round. Leave blank to keep the button as a placeholder.')),
            ],
            options={
                'verbose_name': 'Round link',
                'verbose_name_plural': 'Round links',
                'ordering': ['round_number'],
            },
        ),
    ]
