# Generated by Django 3.1.2 on 2026-02-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='password',
            field=models.CharField(blank=True, help_text='Password required to open this round link.', max_length=128),
        ),
    ]
